### ISSUE TITLE
Document the Python API.

### ISSUE THREAD

**Issue by SimonSapin** [Kozea/CairoSVG#10]
That is all.

**Comment by waldyrious** [comment]
Maybe I'm doing something wrong, but passing a filename to `svg2ps` didn't work. Instead, I had to do:
```python
cairosvg.svg2ps(open("/path/to/input.svg", "rb").read(), write_to="/tmp/output.ps")
```

If this is correct, I'd be happy to submit a PR fixing the documentation, so please confirm. Otherwise, let me know why
```python
cairosvg.svg2ps("/path/to/input.svg", write_to="/tmp/output.ps")
```
didn't work -- I got the following error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/cairosvg/__init__.py", line 43, in <lambda>
    surface_type.convert(*args, **kwargs))(_surface_type)
  File "/usr/local/lib/python3.5/site-packages/cairosvg/surface/__init__.py", line 103, in convert
    tree = Tree(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/cairosvg/parser.py", line 270, in __init__
    tree = ElementTree.fromstring(bytestring)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
not well-formed (invalid token): line 1, column 0
```

At the very least, the error could be more informative -- again, happy to submit a PR if you let me know where / what to change.

**Comment by waldyrious** [comment]
By the way, I also tried navigating to the folder where the input file is and running the script there passing only the filename, without the path, and also adding "file://" to the path (using both the full path and the filename only). None of this worked, so it seems to me a filename isn't actually accepted as input.

**Comment by liZe** [comment]
As described in the [documentation](http://cairosvg.org/documentation/):

> The cairosvg module offers 4 functions:
>
> `svg2pdf`,
> `svg2png`,
> `svg2ps`, and
> `svg2svg`.
>
> These functions expect one of these parameters:
> 
> `bytestring`, a byte string containing SVG, or
> `url`, an URL or a filename, or
> `file_obj`, a file-like object.

You can use:
- `cairosvg.svg2ps(file_obj=open("/path/to/input.svg", "rb").read(), write_to="/tmp/output.ps")`, or
- `cairosvg.svg2ps(url="/path/to/input.svg", write_to="/tmp/output.ps")`

**Comment by SimonSapin** [comment]
`file_obj` without `.read()`, right?

**Comment by liZe** [comment]
Of course, I've changed the comment.
