### ISSUE TITLE
do not support 'utf-8'?

### ISSUE THREAD

**Issue by freetest** [Kozea/CairoSVG#101]
hi

I use cairosvg.svg2png   but  the utf-8 it not show for me?

**Comment by liZe** [comment]
Related to Kozea/pygal#320.

You have to configure the font used by Pygal, and use a font that has the needed glyphs. You'll find information about how to configure the font in [the documentation](http://www.pygal.org/en/latest/documentation/custom_styles.html?highlight=font).
