### ISSUE TITLE
How to choose height and width

### ISSUE THREAD

**Issue by Derpolino** [Kozea/CairoSVG#104]
Hello,

cairosvg.svg2png(url='image.svg', write_to='image.png')

how to set height and width like cli ?

thanks

**Comment by Derpolino** [comment]
Ok cool t'es français ^_^

En faite j'aimerai choisir la taille depuis le code, hors toi tu montres un exemple que en commande :/

**Comment by fnavarrogonzalez** [comment]
After make some test with
cairoSVG /directory/animage.svg -H XX -W YY -o /directory/animage.png
The call doesn't take the width/height.

The call of svg2png need to be  cairosvg.svg2png(url='image.svg', write_to='image.png' parent_width=XX, parent_height=YY) if you read how is parsing the options:

https://github.com/Kozea/CairoSVG/blob/master/cairosvg/__init__.py#L77

**Comment by liZe** [comment]
@Derpolino Documenting the API could help, but reading the source is the best way to know how to use CairoSVG now. Did the previous comment solve your problem?

**Comment by liZe** [comment]
I've merged #107, I think that it'll help you a lot!
