### ISSUE TITLE
Python 2 support dropped early?

### ISSUE THREAD

**Issue by SmileyChris** [Kozea/CairoSVG#106]
With your latest security releases, you've introduced Python 2 backwards incompatibilities that weren't supposed to come until v2. Is there any chance of a security fixed version still Python 2 compatible?

**Comment by liZe** [comment]
I've tried to commit minor changes in the [1.0.x branch](https://github.com/Kozea/CairoSVG/commits/1.0.x). Which commit is not Python2-compatible?

**Comment by SmileyChris** [comment]
Thanks for following up.

I was mixed up as to what was going wrong with weasyprint installation. They had a version out which hadn't pegged python 2 as having a <2 dependency on CairoSVG. Nothing to see here, move along... :cop:

**Comment by liZe** [comment]
> I was mixed up as to what was going wrong with weasyprint installation.

For the record, it's fixed in Kozea/WeasyPrint#323.
