### ISSUE TITLE
Scale doesn't work with SVG files with no viewBox

### ISSUE THREAD

**Issue by BookOwl** [Kozea/CairoSVG#114]
When I try to convert the attached svg to a png, the scale option doesn't make the rendered object any bigger, it just puts more empty space around it.
SVG file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="212" height="212" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="e" fill="#009"><g id="d"><g id="c"><g id="b">
<path id="a" d="m94,19.5 12-19 12,19"/>
<use xlink:href="#a" transform="rotate(11.25 106,106)"/></g>
<use xlink:href="#b" transform="rotate(22.5 106,106)"/></g>
<use xlink:href="#c" transform="rotate(45 106,106)"/>
<path d="m99,30v60h14V30"/></g>
<use xlink:href="#d" transform="rotate(90 106,106)"/>
<path fill="none" stroke="#009" stroke-width="15"
d="m105,92a14,14 0 1,0 2,0zM105,26a80,80 0 1,0 2,0z"/></g>
<use xlink:href="#e" transform="rotate(180 106,106)"/>
</svg>
```
Output file:
![gear](https://cloud.githubusercontent.com/assets/13385064/18447302/0c8fc7c4-78f4-11e6-94f3-3ef5c2abdb46.png)

**Comment by liZe** [comment]
@ricardobeat any idea about that?

**Comment by liZe** [comment]
Thanks for reporting this!

**Comment by BookOwl** [comment]
Your welcome!

**Comment by ricardobeat** [comment]
@BookOwl from my understanding of the spec, the `width / height` attributes define the size of the `<svg>` document - the viewport. The `viewBox` attribute is what allows mapping the path coordinates to any viewport size, without it there is no way to realize this coordinate transformation and the SVG is only usable at it's original size.

**Comment by ricardobeat** [comment]
Late to the party :) @liZe thanks for the fix!
