### ISSUE TITLE
Transparency issues

### ISSUE THREAD

**Issue by con-f-use** [Kozea/CairoSVG#116]
The following code is giving me problems:

```
from PIL import Image
import cairosvg
from io import BytesIO

buff = BytesIO()
cairosvg.svg2png(
    url='http://christoph.ist-stylish.de/_data/misc/orig.svg',
    write_to=buff
)
buff.seek(0)
img = Image.open( buff )
img.save('fail.jpg')
```

Input image:

![](http://christoph.ist-stylish.de/_data/misc/orig.svg)

Output image:

![](http://christoph.ist-stylish.de/_data/misc/fail.jpg)

**Comment by liZe** [comment]
I've got no problem with your image, here's what I get:
![test](https://cloud.githubusercontent.com/assets/952243/18594110/a91ef8d8-7c3e-11e6-966f-63c939f22ea8.png)

So:
- which version of CairoSVG do you have?
- do you have any warnings when launching your script?

If you're using the 1.x version of CairoSVG, you should try to install `lxml`, `tinycss` and `cssselect`. You can find more information in the [old website](https://github.com/Kozea/CairoSVG/blob/website/pages/user_documentation.rst#id2) for 1.x and the [new website](http://cairosvg.org) for the current master/2.0.0rcX.

**Comment by con-f-use** [comment]
Yes, I am on 1.0.22 and have installed the modules recommend. No warnings.

**Comment by liZe** [comment]
> Yes, I am on 1.0.22 using python 2.7.12 and have installed the modules recommend. The later versions of cairosvg don't seem to be on pip or in the Ubuntu repositories. I get no warnings and have above modules (lxml etc.) installed.

Strange. It works for me with 1.0.20 + Python 3.5.2 and 1.0.22 + Python 2.7.11. It works well even without lxml/tinycss/cssselect as the CSS is inline.

> Can you recommend a solution for 1.x.?

As I'm not able to reproduce, I don't really know what to do… :cry:.

**Comment by con-f-use** [comment]
Hmm... then maybe the fault is in pillow? I have version 1.1.7

**Comment by liZe** [comment]
> then maybe the fault is in pillow

Of course, it is! You open a transparent PNG and save it as a JPEG, but JPEG files can't be transparent. Pillow replaces the transparent pixels by black ones. No problem in CairoSVG then :wink:.
