### ISSUE TITLE
Ignore an <image> href if it points to a file that can't be found

### ISSUE THREAD

**Issue by BaconRanch** [Kozea/CairoSVG#118]
If I have an SVG containing hrefs for `<image>` tags that point to nonexistent files on the filesystem, CairoSVG throws an IOError.  It would be nice to at least have the option to ignore these hrefs and produce output that simply doesn't show the referenced image. 

Here's an excerpt from image.py:

```
def image(surface, node):
    """Draw an image ``node``."""
    url = node.get("{http://www.w3.org/1999/xlink}href")
    if not url:
        return
    if url.startswith("data:"):
        image_bytes = open_data_url(url)
    else:
        base_url = node.get("{http://www.w3.org/XML/1998/namespace}base")
        if base_url:
            url = urlparse.urljoin(base_url, url)
        if node.url:
            url = urlparse.urljoin(node.url, url)
        if urlparse.urlparse(url).scheme:
            input_ = urlopen(url)
        else:
            input_ = open(url, 'rb')  # filename
        image_bytes = input_.read()

    if len(image_bytes) < 5:
        return
```

`input_ = open(url, 'rb')  # filename` is the line that throws the exception.

Notice how the last two lines of the excerpt I posted have the function returning if there are fewer than 5 bytes in the input file.  It would be nice to also have the function return if the file isn't found.

```
try:
    input_ = open(url, 'rb')
except IOError:
    return
```

I understand that catching an exception and failing / continuing silently isn't great, but since it's useful in some use cases, could it at least be an option?

**Comment by ErikOnBike** [comment]
With the URLFetcher (#123) it would be possible to solve this without having to change the behaviour of the general code. It could just be added as a parameter to `convert` (see the `kwargs` dictionary being created in the `main` method). Having this as an option is something for Guillaume to decide (pretty simple to implement, @liZe just say the word).

For example:
    class ForgivingURLFetcher(URLFetcher):

        def fetch(self, url):
            try:
                return super().fetch(url)
            except:
                return ''     # Answer empty string (which is okay for image and/or CSS)

Some explanation:
Seeing the above issue I thought it would be nice to be able to catch all kinds of exceptions. CairoSVG will currently fail 'hard' on incorrect input. Trouble is, there is a lot of ground to cover with respect to the potential exceptions. Parsing strings, lookups, out of range values, etc. Handling these gracefully means introducing a great many exception handlers all over the place. Introducing 'safe' defaults (*) or standard behaviour in these handlers is not trivial. Different users might have different needs here. So maybe the above is a useful 'solution' for this specific case. It is not the solution for the larger problem of exceptions, but maybe that is just a bridge too far for now.

(*) Guillaume did already a great job in implementing all relevant parts of the SVG spec. Default values for attributes/properties/styles are already present and should prevent a lot of issues. Unfortunately not all SVG writers will produce SVG files which are compliant to the spec.

**Comment by BaconRanch** [comment]
Yeah, I'm happy with this solution.  Writing a derived class and passing an instance of it in to one of the surface convert methods to get this url-ignoring behavior is fine with me!

**Comment by ErikOnBike** [comment]
The url_fetcher implementation has changed a bit. It is now a function instead of a class instance. It is however still customisable. I have a new pull request (#125) outstanding which differentiates between resource types. This would allow you to ignore unavailable images but still fail on CSS resources being unavailable (although you could off course ignore both if that is what you need ;-).
If you feel the solution is good enough for you, you can close this issue.
