### ISSUE TITLE
svg to png transparency issue

### ISSUE THREAD

**Issue by richiverse** [Kozea/CairoSVG#120]
Hi @liZe 

I'm using ![coverage-badge](https://github.com/dbrgn/coverage-badge) to generate coverage badges for a private repo and am using cairo cli to convert the svg to png. I had to fix some string to float conversions in your source to get it to render. However, I get transparancy issues in the end result.

I run the following in bash to do the conversion:

``` bash
cairosvg coverage.svg -o coverage.py
```

source = 

```
<svg xmlns="http://www.w3.org/2000/svg" width="99" height="20">
    <linearGradient id="b" x2="0" y2="100%">
        <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
        <stop offset="1" stop-opacity=".1"/>
    </linearGradient>
    <mask id="a">
        <rect width="99" height="20" rx="3" fill="#fff"/>
    </mask>
    <g mask="url(#a)">
        <path fill="#555" d="M0 0h63v20H0z"/>
        <path fill="#a4a61d" d="M63 0h36v20H63z"/>
        <path fill="url(#b)" d="M0 0h99v20H0z"/>
    </g>
    <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
        <text x="31.5" y="15" fill="#010101" fill-opacity=".3">coverage</text>
        <text x="31.5" y="14">coverage</text>
        <text x="80" y="15" fill="#010101" fill-opacity=".3">61%</text>
        <text x="80" y="14">61%</text>
    </g>
</svg>
```

What it should look like:

![coverage](https://camo.githubusercontent.com/3843f0be71f93116d3b698d6322b00015c4c129a/68747470733a2f2f63646e2e7261776769742e636f6d2f646272676e2f636f7665726167652d62616467652f6d61737465722f6578616d706c652e737667)

what the source above gets rendered as:
![coverage](https://cloud.githubusercontent.com/assets/2671102/19546207/be9caa98-965b-11e6-841d-701cfe5f541b.png)

Any idea what I'm doing wrong here?

**Comment by ErikOnBike** [comment]
Hi @richiverse ,

You're not doing anything wrong. Instead you've managed to find 2 bugs in CairoSVG!

1. The type conversion you mentioned yourself.
2. An incorrect reference to width where height was expected (and vice versa) in deciding the size of the mask applied.

I think I have fixed them and sent a pull request to @liZe

**Comment by ErikOnBike** [comment]
The result I get with the fixes applied.
![coverage](https://cloud.githubusercontent.com/assets/5963296/19829663/f65cadd2-9de7-11e6-8bb7-5c5b22910aa3.png)

(Your example of what it should look like has 24% as text instead of 61%, but I assume it is taken from another example and not your own provided svg ;-)

**Comment by ErikOnBike** [comment]
@richiverse did the latest update solve your problem? If so, we can close this issue ;-).

**Comment by ErikOnBike** [comment]
Guillaume,

This issue can be closed I suppose.

Cheers,
Erik
