### ISSUE TITLE
<text> inside inner <svg> elements is not rendered

### ISSUE THREAD

**Issue by anytimecoder** [Kozea/CairoSVG#127]
Hi,

I'm trying to render png using CairoSVG through bash command:

`cairosvg a.svg -o a.png`

the SVG source is as follows:
```
<svg id="svg-a" width="600" height="600">
    <defs/>
    <svg viewBox="0 0 547 185" x="24" y="383" height="185" width="547">
        <rect x="0" y="0" height="100%" width="100%" fill="#ccc"/>
        <text
            fill="#000000"
            width="547"
            height="185"
            font-size="14"
            x="0"
            y="50%"
            text-anchor="start">
            <tspan x="0" dy="-3em">Text Text Text Text Text Text Text Text Text Text Text Text Text Text</tspan>
            <tspan x="0" dy="1em">Text Text Text Text Text Text Text Text Text Text Text Text Text Text</tspan>
            <tspan x="0" dy="1em">Text Text Text Text Text Text Text Text Text Text Text Text Text Text</tspan>
            <tspan x="0" dy="1em">Text Text Text Text Text Text Text Text Text Text Text Text Text Text</tspan>
            <tspan x="0" dy="1em">Text Text Text Text Text Text Text Text Text Text Text Text Text Text</tspan>
            <tspan x="0" dy="1em">Text Text Text Text Text Text Text Text Text Text Text Text Text Text</tspan>
            <tspan x="0" dy="1em">Text Text Text Text Text Text Text Text Text Text Text Text Text Text</tspan>
        </text>
    </svg>
</svg>
```

The result is this: [Link to image on Dropbox](https://www.dropbox.com/s/42529ksvvak5sxl/a.png?dl=0)

The `rect` is rendered correctly where it's supposed to be, but no text

**Comment by anytimecoder** [comment]
I've just narrowed above problem to `text` attribute `y=50%`: without it text is rendered. So my guess is the problem is in percentage?

**Comment by ErikOnBike** [comment]
Hi,

Problem is indeed the `y="50%"`. It is calculated based on the height of the outer svg (i.e. based on value `600`). If you change it to `y="5%"` you will see part of the text (still wrong in exact location). I do not have time to try and fix this now. If you are interested please have a look (`svg.py` is where the inner svg is created, `helper.py` is where the y-position is calculated in the function `size`).

**Comment by anytimecoder** [comment]
Ok, I'll have a look

**Comment by liZe** [comment]
Thanks for reporting!

**Comment by anytimecoder** [comment]
that was quick :)
