### ISSUE TITLE
Additional dependencies for installing

### ISSUE THREAD

**Issue by anoop901** [Kozea/CairoSVG#130]
I tried installing `cairosvg` in a `virtualenv` on "Bash on Ubuntu on Windows 10". However, it didn't work until I installed the following additional dependencies:

```
sudo apt-get install python3-dev python3-lxml libxml2-dev libxslt1-dev zlib-dev libcairo2
```

As far as I can tell, building/installing `lxml` (a dependency of `cairosvg`) required `libxml2-dev`, `libxslt1-dev`, and `zlib-dev`. Also, `libcairo2` was a runtime dependency. I'm not sure if all of these are strictly required, though -- these are just what I happened to install before I got `cairosvg` to work. None of these are mentioned in the installation documentation, yet `cairosvg` didn't work until I installed all of them. Should they be added to the documentation?

**Comment by liZe** [comment]
Thanks for reporting. Yes, it should be added to the documentation.

**Comment by liZe** [comment]
It's been in the documentation for a while now.
