### ISSUE TITLE
Custom fonts problem on Ubuntu

### ISSUE THREAD

**Issue by in-memory** [Kozea/CairoSVG#136]
I'm converting SVG with custom fonts to PNG. 
The following code works fine on local OS X with the fonts installed in the system
`import cairosvg`
`png_content = cairosvg.svg2png(bytestring=svg_content)`

However, the same code doesn't work on remote Ubuntu instance (the fonts are also installed) and custom fonts get replaced by default ones.

**Comment by liZe** [comment]
A common reason for this is having the fonts installed for an user and launching CairoSVG with another user.

**Comment by in-memory** [comment]
Thanks for the tip, I will check it when I have an opportunity. Switched to ImageMagick for now.

**Comment by liZe** [comment]
Closing for now. @in-memory if you have more information, please reopen this issue.

**Comment by lbluitt** [comment]
Having the same issue. Any ideas?
I'm listing the fonts in cache (fc-list) and I see my font is installed in Ubuntu (in a docker image) but when converting an SVG into a PNG the font is replaced for default font. I'm installing the font in the path usr/local/share/fonts and also usr/share/fonts.This issue does not happen in my local machine.
