### ISSUE TITLE
Install fail on Mac

### ISSUE THREAD

**Issue by pathumego** [Kozea/CairoSVG#138]
on macOs 10.12.1

```  
Collecting cairosvg
  Downloading CairoSVG-2.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-EbHAMx/cairosvg/setup.py", line 24, in <module>
        with open(init_path, 'r', encoding='utf-8') as fd:
    TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by liZe** [comment]
CairoSVG 2.0+ only works with Python 3.4+, I suppose that you're trying to install it with Python 2.7.

If you can't use Python 3.4+, you can install CairoSVG 1.0.22.

**Comment by pathumego** [comment]
@liZe Thanks!

**Comment by liZe** [comment]
@xiaolvtaomi There's a problem between pypi.python.org's certificate and your system. The certificate works for me, you can probably fix your problem by updating your root certificates.

**Comment by ndharmateja** [comment]
@liZe : Can you please tell me how to install CairoSVG 1.0.22 for MacOS? It would be of great help.
