### ISSUE TITLE
external links to css or images produce wrong URI in Windows

### ISSUE THREAD

**Issue by markmal** [Kozea/CairoSVG#139]
When there is external (not embedded) CSS file
```
<?xml-stylesheet href="mystyle.css" type="text/css"?>
```

then in Windows it produces wrong URI for mystyle.css that cannot be resolved further by request.py.

Please modify in your url.py following procedure
```
def read_url(url, url_fetcher, resource_type):
    """Get bytes in a parsed ``url`` using ``url_fetcher``.

    If ``url_fetcher`` is None a default (no limitations) URLFetcher is used.
    """
    if url.scheme:
        url = url.geturl()
    else:
        ##url = 'file://{}'.format(os.path.abspath(url.geturl())) # this does not work in Windows
        abspath = os.path.abspath(url.geturl())
        url = urljoin('file:', pathname2url(abspath))
    return url_fetcher(url, resource_type)
```

**Comment by liZe** [comment]
For the record: see #135.

**Comment by saluk** [comment]
@liZe are there plans to merge that fix, as this seems to still be an issue? I can't use this project at all at the moment as no image references are working on windows.

**Comment by liZe** [comment]
@saluk Thank you for the PR! I've merged it and cleaned a couple of things, could you tell me if it works for you (and close this issue)?

**Comment by liZe** [comment]
Let's say it works.
