### ISSUE TITLE
CairoSVG not have surface

### ISSUE THREAD

**Issue by juwen** [Kozea/CairoSVG#140]
l installed CairoSVG 2.0.1(pip install CairoSVG).
and have Error:
```
Traceback (most recent call last):
  File "D:/work/lean_python/pdf/other.py", line 2, in <module>
    import cairosvg
  File "D:\env_python352\lib\site-packages\cairosvg\__init__.py", line 29, in <module>
    from . import surface
  File "D:\env_python352\lib\site-packages\cairosvg\surface.py", line 24, in <module>
    import cairocffi as cairo
  File "D:\env_python352\lib\site-packages\cairocffi\__init__.py", line 46, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2')
  File "D:\env_python352\lib\site-packages\cairocffi\__init__.py", line 43, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2
```

**Comment by elzapp** [comment]
CairoSVG (the python library and bindings) needs Cairo (The C library, part of GTK+) to run. It appears you don't have it an it's headers installed on your system.

Judging by the paths in the traceback, I assume you are on windows. I'm not on windows currently, and haven't used Cairo on windows. But this article could be helpful:

https://blogs.gnome.org/nacho/2014/08/01/how-to-build-your-gtk-application-on-windows/
(it was referenced from here: https://www.gtk.org/download/windows.php)

**Comment by juwen** [comment]
Hi,elzapp
I have installed Cairo.
 cairo.cairo_version_string() == 1.14.8
cairo.version == 1.10.0

**Comment by liZe** [comment]
Hi @juwen,

Installing Cairo on Windows and using it with Python can cause many problems, this bug is well known and has been reported many times.

Hopefully, there's a solution. You can **carefully** follow the steps of [the WeasyPrint documentation](http://weasyprint.readthedocs.io/en/latest/install.html#windows), replacing `python -m pip install weasyprint` by `python -m pip install cairosvg`.

**Comment by liZe** [comment]
Can I close this issue, @juwen?
