### ISSUE TITLE
CairoSVG is unable to parse 'textPath' within SVG

### ISSUE THREAD

**Issue by plahoti** [Kozea/CairoSVG#144]
With reference to https://github.com/Kozea/pygal/issues/369

The PNG/PDF generation from the SVG (which can be viewed here: https://codepen.io/anon/pen/vxWYJX) seems to render undesired output because of the usage of 'textPath' in the SVG.
In the above example, the text '100%' gets rendered incorrectly as compared to the original SVG.

![gauge](https://cloud.githubusercontent.com/assets/16802795/24092357/d232ae42-0d73-11e7-8b19-c5bfd3ee0b09.png)

**Comment by liZe** [comment]
Thank you for reporting this issue! `text-align` was not handled correctly with texts on paths. It's fixed, 2.0.2 has been released.

**Comment by plahoti** [comment]
Thanks @liZe for getting this fixed.
I would like to get your inputs on the following.

Scenario: I have been using CairoSVG 1.0.22 version as I'm constrained with using Python 2.7. I need this fix to be able to use the library. Please comment on the possible approaches as listed.
1. Cherry-picking this fix in CairoSVG 1.0.22
2. Running CairoSVG 2.0.2 over Python 2.7 (although the Python2 support has been dropped). Would like to understand the implications of doing it.

Thanks in advance.

**Comment by liZe** [comment]
Cherry-picking is the best solution between 1 and 2, as 2.0.x versions are really far from working with Python 2. Here's the patch of the two commits fixing this issue:

```diff
diff --git a/cairosvg/text.py b/cairosvg/text.py
index 3025f7e..785862a 100644
--- a/cairosvg/text.py
+++ b/cairosvg/text.py
@@ -160,9 +160,9 @@ def text(surface, node):
         surface.stroke_and_fill = True
         cairo_path = surface.context.copy_path_flat()
         surface.context.new_path()
-        length = path_length(cairo_path)
+        length = path_length(cairo_path) + x_bearing
         start_offset = size(surface, node.get('startOffset', 0), length)
-        surface.text_path_width += start_offset
+        surface.text_path_width += start_offset - x_align
         bounding_box = extend_bounding_box(bounding_box, ((start_offset, 0),))
 
     if node.text:
```

It should be quite easy to "backport" it for the 1.0.x branch.

But the only real solution is to port your code to Python 3. Version 3.0 has been released in 2008, 2.7 support will be dropped in 2020. If you're stuck with 2.7, you'll get bigger and bigger problems, CairoSVG is just the beginning :wink:.

**Comment by plahoti** [comment]
I can understand your point. But, my hands are tied too.

Meanwhile, CairoSVG 1.0.22 seems to generate the following PNG unlike the one which used to get generated earlier. Has anything changed overnight?
![gauge](https://cloud.githubusercontent.com/assets/16802795/24141750/6812b4b2-0e4a-11e7-9a84-ab6e4fc31edb.png)

**Comment by liZe** [comment]
> Has anything changed overnight?

In 1.0.22? Not at all.
