### ISSUE TITLE
Trouble rendering some svg in png

### ISSUE THREAD

**Issue by JGiard** [Kozea/CairoSVG#148]
Hi,
I use cairosvg to build preview-able images on my svg files. It works fine most of the time but recently I stumbled upon a particular set of images that do not render properly.
[sample.zip](https://github.com/Kozea/CairoSVG/files/952132/sample.zip)
The most visible problem is that some text is not rendered at the proper size.

I don't really know how to investigate this problem.

I can get the images to render properly when using librsvg (rsvg-convert) so it seems more like a problem in cairosvg than libcairo but I don't known much about who is in charge of what in term of libraries.
The images appear to have been generated using microsoft Visio.

I'm using cairosvg 2.0.2 with libcairo 1.14.6 (btw the website is not up-to-date with 2.0.2 release)

Any help will be greatly appreciated !

**Comment by simonxeko** [comment]
In your svg I saw `.st2 {fill:#000000;font-family:Calibri;font-size:0.666664em}` in style tag, changing **0.666664em** to **12px** `.st2 {fill:#000000;font-family:Calibri;font-size:12px}`
will generate readable results. 

So probably the default em needs to be defined in your file, and it seems that SVG1.1 spec does not specific what the value should be.

**Comment by liZe** [comment]
> So probably the default em needs to be defined in your file, and it seems that SVG1.1 spec does not specific what the value should be.

It's true. CairoSVG uses 12pt = 16px as default value, rsvg probably uses 12px.

**Comment by JGiard** [comment]
Thank you for the explanation.
