### ISSUE TITLE
output_width and output_height ignored if SVG doc defines them

### ISSUE THREAD

**Issue by dom3d** [Kozea/CairoSVG#164]
cairosvg.svg2png(url='./test.svg', write_to='./test.png', parent_width=200, parent_height=200)

If the svg document defines it's size e.g. "<svg width="800" height="800" " then the document size is used (800x800) instead the ones given into the function (200x200). I think it should be possible to override / define the target sizes regardless of what the SVG document defines.

**Comment by liZe** [comment]
`parent_width` and `parent_height` are properties used to define the size of the parent of the SVG (for example when embedding in HTML documents), not the size of the SVG.

It's actually possible to override the size of the SVG using the `scale` parameter. But if you want to override the size (or anything else) independently from the current values, the easiest way is probably to edit the SVG.

**Comment by johschmitz** [comment]
I also have this problem and it is extremely annoying to work around it with low level XML parsing etc.
It should really be possible to provide either a fixed witdh or a fixed height and scale the output accordingly while maintaining the same aspect ratio given by the original SVG width and height. As far as I can see that is not possible only with the `scale` parameter?

**Comment by liZe** [comment]
> As far as I can see that is not possible only with the `scale` parameter?

Since 2.2.0, you can also use the `output-width` and `output-height` parameters.

**Comment by johschmitz** [comment]
It seems to be impossible when the input file already has a width and height defined. The output_width and output_height need to overwrite those values if set in the function call.

**Comment by debuglevel** [comment]
Are there any workarounds?

**Comment by spajak** [comment]
It's useless if I have to use another tool to resize resulting PNG... Please allow simple overwriting of width & height.

**Comment by liZe** [comment]
Hmmm… `output-width` and `output-height` actually overwrite width and height set in the SVG tag. It works if you give both of them. @debuglevel @spajak @johschmitz Doesn’t it work for you?

**Comment by johschmitz** [comment]
I need to check if maybe it works with a new version. If it wasn't fixed then it is indeed a big issue. Could be that some people are still suffering from this since they are using an older version bundled with their distro.

**Comment by liZe** [comment]
> Could be that some people are still suffering from this since they are using an older version bundled with their distro.

I’m not sure. Code hasn’t changed since the feature has been added by #193.

**Comment by johschmitz** [comment]
Since commit #193 is from 2018 I would strongly assume at this point that the bug persists. Need to have a look to be certain.

**Comment by spajak** [comment]
> Hmmm… `output-width` and `output-height` actually overwrite width and height set in the SVG tag. It works if you give both of them. @debuglevel @spajak @johschmitz Doesn’t it work for you?

Yes it works, just tested. You have to specify both.
I was thinking specifying only height would calculate width accordingly to aspect ratio.. I know I could use scale, but I had a lot of variable sized svg files.. and the scale would be different for every file... That would be a nice feature for me.

**Comment by liZe** [comment]
> I was thinking specifying only height would calculate width accordingly to aspect ratio.

Done! Please tell us if it fits your needs.
