### ISSUE TITLE
Embedded SVG in SVG is not working.

### ISSUE THREAD

**Issue by whorainzone** [Kozea/CairoSVG#165]
Embedded SVG in SVG is not working.
Am I doing it wrong?

[a4_landscape.tar.gz](https://github.com/Kozea/CairoSVG/files/1479721/a4_landscape.tar.gz)

**Comment by liZe** [comment]
That's probably a bug in the way CairoSVG handles embedded SVGs, the `viewBox` with negative values is a case that's probably not tested yet!

**Comment by aziesemer** [comment]
> That's probably a bug in the way CairoSVG handles embedded SVGs, the `viewBox` with negative values is a case that's not tested yet for sure!

This bug is fixed with PR #198. 
However, I notice that the text alignment is wrong. CairoSVG may have trouble with text attribute dominant-baseline="central".
Please refer to https://github.com/webcompat/web-bugs/issues/19203 since some web browsers have trouble too (Chrome is fine).
