### ISSUE TITLE
font-size with em units is scaled badly if converted to png

### ISSUE THREAD

**Issue by eviljeff** [Kozea/CairoSVG#168]
An svg specifies `font-size` meaurements in `em` unit the scaling is all wrong.  Text rendered in 2em should be twice as tall as 1em.  

```xml
<svg width="580" height="400" xmlns="http://www.w3.org/2000/svg">
 <!-- Created with Method Draw - http://github.com/duopixel/Method-Draw/ -->
 <g>
  <title>background</title>
  <rect fill="#fff" id="canvas_background" height="402" width="582" y="-1" x="-1"/>
  <g display="none" overflow="visible" y="0" x="0" height="100%" width="100%" id="canvasGrid">
   <rect fill="url(#gridpattern)" stroke-width="0" y="0" x="0" height="100%" width="100%"/>
  </g>
 </g>
 <g>
  <text xml:space="preserve" text-anchor="start" font-family="Helvetica, Arial, sans-serif" font-size="1em" id="svg_1" y="150" x="104.5" fill="#000000">1em</text>
  <text xml:space="preserve" text-anchor="start" font-family="Helvetica, Arial, sans-serif" font-size="2em" id="svg_2" y="180" x="104.5" fill="#000000">2em</text>
 </g>
</svg>
```
CairoSVG output:
![method](https://user-images.githubusercontent.com/768592/33497499-0a5af880-d6c6-11e7-93a9-f029dc8cd391.png)

Firefox:
![method-firefox](https://user-images.githubusercontent.com/768592/33497514-151dd0e4-d6c6-11e7-9704-a836d8ff1389.png)

**Comment by liZe** [comment]
I'm so sorry…

I don't know how it's even possible to get HUGE errors like this one with the number of tests from the W3C suite included in CairoSVG.
