### ISSUE TITLE
Images not correctly handled

### ISSUE THREAD

**Issue by liZe** [Kozea/CairoSVG#17]
See: https://github.com/Kozea/CairoSVG/tree/master/test/fail/image/.

**Comment by Chris-May** [comment]
Looks like one problem is that if PIL is not present, it will fail silently in `./surface/images.py`:
```python
try:
    from PIL import Image
    png_file = BytesIO()
    Image.open(BytesIO(image_bytes)).save(png_file, 'PNG')
    png_file.seek(0)
except:
    # No way to handle the image
    return
```

When I forked the repo, I can't find that file, so is it being imported by another source?

**Comment by liZe** [comment]
The current master branch of the repository is a pre-2.0 version, with a lot of things rewritten or displaced. In this new version, PIL is mandatory and the image management is done in `cairosvg/image.py`.

**Comment by Chris-May** [comment]
Thanks for letting me know! Though I'm confused. Where is this newer version?

**Comment by Chris-May** [comment]
Oh! I installed this through the cheese shop. I guess I should pull from this repo instead?

**Comment by liZe** [comment]
This new 2.0 version is not released yet on PyPI, but you can try it right now: it's the master branch of the repository, you just have to clone it :).

If you're interested in the new features of the future 2.0 version, here's the changelog: https://github.com/Kozea/CairoSVG/blob/master/NEWS.rst.

**Comment by liZe** [comment]
> Oh! I installed this through the cheese shop. I guess I should pull from this repo instead?

Yes

**Comment by Chris-May** [comment]
Great! I hope to try it in a couple of hours.
Thank you very much for your help!
