### ISSUE TITLE
Rendering issue when using T command in Path Element 

### ISSUE THREAD

**Issue by simonxeko** [Kozea/CairoSVG#170]
Hi,

Thanks for maintaining this project, this is the most completed opensource svg parser I've seen.

So I got a little issue when I rendered this svg, which is generated by adobe illustrator
https://gist.github.com/simonxeko/94059a5174cfb965ec536097494f0a3a

Here is its output:
![wrong](https://user-images.githubusercontent.com/8991445/34454067-9d338ae4-ed9d-11e7-9879-32656893e574.png)

And this is what it should be:
![correct](https://user-images.githubusercontent.com/8991445/34454070-a41540dc-ed9d-11e7-85d4-4501f9092b92.png)

So under path.py I found:
```
elif letter == 'T':
            # Quadratic curve end
            abs_x, abs_y = current_point
            if last_letter not in 'QqTt':
                x2, y2, x3, y3 = abs_x, abs_y, abs_x, abs_y
            elif last_letter in 'qt':
                x2 += x1
                y2 += y1
            x2 = 2 * abs_x - x2
            y2 = 2 * abs_y - y2
```

Through my understanding to the code, changing to this will fix the issue:
```
elif letter == 'T':
            # Quadratic curve end
            abs_x, abs_y = current_point
            if last_letter not in 'QqTt':
                x2, y2, x3, y3 = abs_x, abs_y, abs_x, abs_y
            elif last_letter in 'qt':
                x2 = abs_x + x2
                y2 = abs_y + y2
```

I am not 100% sure this is the right solution... anyway, this is a rare bug generated by illustrator when converting fonts into path.

**Comment by liZe** [comment]
> Thanks for maintaining this project, this is the most completed opensource svg parser I've seen.

Thank you!

> So I got a little issue when I rendered this svg, which is generated by adobe illustrator […] Through my understanding to the code, changing to this will fix the issue

Thanks for both the report and the patch! I've updated the code to look more like the `'t'` case above, but that's equivalent to your fix.
