### ISSUE TITLE
Auto-completion is unavailable in IDE (double lambda ninja-closure)

### ISSUE THREAD

**Issue by Alphare** [Kozea/CairoSVG#174]
Hi !

Auto-complete is really useful as a productivity tool. I expect to be able to type `cairosvg.<SHORTCUT>` and get all methods from the top module, and `cairosvg.svg2png(<SHORTCUT>` and get all arguments for this function.
I don't know if Python offers some way of documenting this without changing the code back to non-dynamic methods... but I figure the benefit of good autocompletion (which is a form of self-documentation really) and easier to read source code outweighs the cleverness of the main method generating loop. 

I would be glad to help with the issue should you need help. :)

**Comment by liZe** [comment]
> easier to read source code outweighs the cleverness of the main method generating loop

Cleverness is a kind way to say useless complexity :stuck_out_tongue:.

**Comment by Alphare** [comment]
I was trying to be nice 😄 
Thanks for the quick fix, I'll check that out soon.

**Comment by Alphare** [comment]
I've tried the new version, and while having the method names autocomplete is nice, there still isn't any help with arguments: `*args, **kwargs` is not a very helpful signature. Is there any backwards-incompatible reason why we couldn't change these signatures to the "real ones"?

Thanks

**Comment by liZe** [comment]
> Is there any backwards-incompatible reason why we couldn't change these signatures to the "real ones"?

It's not a compatibility issue. The problem is that the 4 `svg2*` functions have (almost) the same docstring. I don't want to duplicate the docstring, but the only easy solution I've found is to set the `__doc__` attribute at runtime. If there's another solution that works with the completions, I'd be OK with it!

**Comment by Alphare** [comment]
I think most IDEs will infer arguments not by the docstring but by the actual signature of the method. 
So going from 
```
def svg2svg(*args, **kwargs):
    return surface.SVGSurface.convert(*args, **kwargs)
```
to 
```
def svg2svg(bytestring=None, otherArg=None, **kwargs):
    return surface.SVGSurface.convert(bytestring=None, otherArg=None, **kwargs)
```
will yield the expected result without changing the docstring.

Maybe I don't fully understand what the problem is.

**Comment by Alphare** [comment]
Isn't it possible to do `(bytestring=None, *, dpi=96)` to force a keyword-only call?

**Comment by liZe** [comment]
> Isn't it possible to do (bytestring=None, *, dpi=96) to force a keyword-only call?

Yes, it is! I've listed all the parameters and used the star to catch unnamed args, updated the docstring, and tests pass (at least with 3.6). `__init__.py` is a bit verbose, but it's much better to get a real signature. Thank you!

**Comment by Alphare** [comment]
Ah wonderful! I'll be sure to let you know how it performs in my IDE when I get a chance 👍

**Comment by Alphare** [comment]
https://github.com/Kozea/CairoSVG/blob/937f146a390aa8c93c0468bff556628461638004/cairosvg/__init__.py#L43

@liZe Did you forget to pass the `unsafe` argument?

**Comment by Alphare** [comment]
This is very nice to have. I remember getting frustrated with the lack of completion (and even false-positives for missing methods), this is great!

![cairosvg_new_signatures](https://user-images.githubusercontent.com/9445758/35555533-c1495782-059f-11e8-8b65-574adfaed3b0.png)

![cairosvg_new_signatures_2](https://user-images.githubusercontent.com/9445758/35555538-c3a7c374-059f-11e8-970b-78e77fa1ae43.png)

**Comment by liZe** [comment]
> @liZe Did you forget to pass the unsafe argument?

Oops!

> This is very nice to have.

Thanks for the screenshots, it's a much better reward than the repetitive code of the commits :wink:!
