### ISSUE TITLE
CJK characters can't be rendered properly

### ISSUE THREAD

**Issue by qwqVictor** [Kozea/CairoSVG#175]
In a SVG, there might be some text inside it. But CairoSVG can't process it properly if there are any CJK characters in it.

In my API, I used CairoSVG command line tool to generate PNG format formulas. CJK characters only hold half size's places.

[Sample.zip](https://github.com/Kozea/CairoSVG/files/1680504/Sample.zip)

**Comment by kashitaka** [comment]
Although it is too old issue, I had a same issue and resolved it.

CairoSVG seems to use fonts installed in your system. If your svg specifys fonts that aren't installed your system, CarioSVG would render a PNG image with default font that doesn't contain CJK. Therefore, you need to check which fonts installed in your system and specify it in `font-family` attribute in svg. 

In Ubuntu environment, 
- You can find fonts that are installed your system with `fc-list` command, and you might found some CJK fonts such as `Noto Sans Mono CJK JP`. 
- Then, you edit `font-family` attribute in `svg` tag by using regexp or something, like `font-family: Noto Sans CJK JP;`.

Now that CairoSVG will resolve installed fonts and render CJK characters properly.
