### ISSUE TITLE
Antialiasing

### ISSUE THREAD

**Issue by Overdrivr** [Kozea/CairoSVG#180]
An SVG rendered with `cairosvg.svg2png` and saved to a file differs to the SVG image saved to a bytestring and converted to a numpy array. It seems that the bytestring approach has no antialiasing.

```
image_data = cairosvg.svg2png(bytestring=tree.encode('utf-8'))
image = Image.open(BytesIO(image_data))
arr = np.array(image).transpose((2, 0, 1))
# Strip alpha channel
arr = arr[:3]
```

Image below is the difference between both outputs (**please click on the image and zoom in because the difference is only visible at edges**):

![diff](https://user-images.githubusercontent.com/1294805/35918480-3e8dd808-0c12-11e8-8618-62c5de9bee40.png)

Any idea why the bytestring output lacks antialiasing ?

**Comment by liZe** [comment]
I don't really know why you get different antialiasing results when generating a bytestring or a file, but I know that Cairo uses different antialiasing settings depending on the output format. For some reason, it may choose different filters for these 2 cases.

If you want to force antialiasing, you may want to play with [`shape-rendering`](https://www.w3.org/TR/SVG/painting.html#ShapeRenderingProperty) and [`text-rendering`](https://www.w3.org/TR/SVG/painting.html#TextRenderingProperty).

**Comment by liZe** [comment]
> If you want to force antialiasing, you may want to play with shape-rendering and text-rendering.

@Overdrivr Did you try these attributes?

**Comment by Overdrivr** [comment]
I did not, in the end my application did not need pixel-perfect renders so I just went with the result. Thanks for sharing those flags, I will try and see what happens

**Comment by liZe** [comment]
Feel free to reopen if needed.
