### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by jkua** [Kozea/CairoSVG#182]
I am having problem converting [this SVG](https://www.dropbox.com/s/v49iq7tqjene9tq/test.svg?dl=0):
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 64">
    <path d="M94,43.89q-.23,9.33,8.83,13l-3.32,6.68Q86.53,58.76,86,43.89V7.47h8V9.82a9.28,9.28,0,0,1,6.94-2.66q15.24.3,15.25,20,0,18.89-15.09,18.89A12.16,12.16,0,0,1,94,43.89Zm6.83-29A7.38,7.38,0,0,0,94,18.66V35.35a8.37,8.37,0,0,0,7.06,3.57q7.13-.07,7.21-11.84T100.83,14.94Z"></path>
</svg>`

Using `cairosvg test.svg -o test.png` I get a misshapen loop:
![test](https://user-images.githubusercontent.com/2237113/36414238-80a012b0-15d6-11e8-87fd-91de94918674.png)

I get the same result when converting to PDF.

Inkscape and Chrome both render it properly:
![test2](https://user-images.githubusercontent.com/2237113/36414557-8d144aba-15d7-11e8-939b-3b0c53138190.png)

I am using CairoSVG 2.1.3 on Mac OS X 10.13.2 with Python 3.6.4

The problem seems to be in the quadratic bezier "T" element at the very end.

**Comment by liZe** [comment]
Thank you for this bug report.

> The problem seems to be in the quadratic bezier "T" element at the very end.

It is. OMG, who is mixing relative and absolute quadratic beziers :wink:?

**Comment by jkua** [comment]
Thanks! I checked out the master branch and it worked great!
> It is. OMG, who is mixing relative and absolute quadratic beziers 😉?

I suspect Adobe - this was part of a logo and I know those guys are using the Creative Suite.
