### ISSUE TITLE
cairosvg does not install with pip3 install cairosvg

### ISSUE THREAD

**Issue by tlk13** [Kozea/CairoSVG#183]
Hi all, 

I have been trying to install cairosvg using the "pip3 install cairosvg" command. 

I always get the error term 

> "python setup.py egg_info" failed with error code 1 in 

and then depending on whether I had run it with sudo powers or not, I get listed the folders
> /private/tmp/pip-build-19ynye6w/cairocffi/ (for sudo)

or 

> /private/var/folders/z8/0m4tj0x14yb75l37vybt1zx00000gp/T/pip-build-zc8buluu/cairocffi/ (for non sudo)

I have tried everything from updating the pip3 setuptools to installing brew and trying to install cairosvg that way.
What would you recommend?

**Comment by liZe** [comment]
Hi,

Could you provide the full stacktrace, please?

**Comment by tlk13** [comment]
@liZe of course, sorry for not including in the first place

This is the output after typing the command 
> pip3 install cairosvg

![cairosvg failure to install](https://user-images.githubusercontent.com/36789465/36630292-1100c06a-195c-11e8-9143-e6a7775a1217.jpg)

**Comment by liZe** [comment]
There's a certificate error when trying to download Python packages. This [StackOverflow](https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify) thread will help you to fix that!

**Comment by tlk13** [comment]
Thank you so much! It worked out perfectly!
