### ISSUE TITLE
Strange tarball name on PyPI

### ISSUE THREAD

**Issue by dotlambda** [Kozea/CairoSVG#188]
Why is the tarball for version 2.1.3 called `CairoSVG-2.1.3.linux-x86_64.tar.gz`?
See https://pypi.org/project/CairoSVG/2.1.3/#files.

**Comment by liZe** [comment]
> Why is the tarball for version 2.1.3 called CairoSVG-2.1.3.linux-x86_64.tar.gz?

My bad, that was a binary tarball, not the source. I've uploaded the source now. Thank you for this issue!
