### ISSUE TITLE
Does not work with non-cffi cairo (AttributeError)

### ISSUE THREAD

**Issue by haael** [Kozea/CairoSVG#195]
The library does not work with normal cairo bundled with Ubuntu. The objects of normal cairo library are not standard Python objects who have __dict__ and unlike cfficairo can no be added custom attributes.

The bug is the file image.py. It can be fixed by not adding the attribute to the cairo ImageSurface object and using a normal variable instead.

In lines 97, 98 and 119 the attribute "image_surface.pattern" should be replaced i.e. with local variable "image_surface_pattern".

**Comment by liZe** [comment]
Recent versions of CairoSVG are not designed to work with [Pycairo](https://pycairo.readthedocs.io/en/latest/) (what you call the "normal" cairo library) but with [CairoCFFI](https://cairocffi.readthedocs.io/en/stable/).

Even if Pycairo and CairoCFFI share most of their API, and even if CairoSVG used to work with Pycairo, there's no roadmap now to make CairoSVG work with Pycairo again.

Short answer: please use CairoCFFI :smile:.
