### ISSUE TITLE
text alignment-baseline="hanging" is not rendering correctly 

### ISSUE THREAD

**Issue by amir20** [Kozea/CairoSVG#196]
Hi there! I am trying to render a very a simple SVG and it almost works. I wonder if I am doing something wrong. 

Here is the SVG file. 

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="50" version="1.1">
    <style>
        /*
        <![CDATA[ */
        text {
            font-family: Helvetica;
            fill: #333;
        }
        /* ]]>
        */
    </style>
    <defs>
        <linearGradient id="background" x1="0%" x2="100%" y1="0%" y2="20%">
            <stop offset="0%" style="stop-color:#ffaf24;stop-opacity:1"/>
            <stop offset="71%" style="stop-color:#fffa70;stop-opacity:1"/>
        </linearGradient>
    </defs>
    <rect width="100%" height="100%" fill="url(#background)" rx="3" ry="3"/>
    <image width="30" height="30" x="7" y="8" xlink:href="{{ base64_png(clan.badgeUrls.small) }}"/>
    <text x="45" y="10" alignment-baseline="hanging" font-size="18">
        {{ clan.name }}
    </text>
    <text x="45" y="30" alignment-baseline="hanging" font-size="12" xml:space='preserve'>{{ "{:,.1f}".format(clan.clanPoints/1000) }}k trophies  {{ "{:,.1f}".format(clan.total_attack_wins/1000) }}k wins</text>
</svg>
```

This gets rendered with Flask as this: 

<img width="252" alt="screen shot 2018-06-30 at 5 16 18 pm" src="https://user-images.githubusercontent.com/260667/42129971-55072a48-7c89-11e8-8bc5-ef92d25d65e8.png">

But when I render it as PNG I see:
<img width="267" alt="screen shot 2018-06-30 at 5 16 50 pm" src="https://user-images.githubusercontent.com/260667/42129972-6a879448-7c89-11e8-8bd2-866b11339e4f.png">

I wonder if `alignment-baseline="hanging"` is not being rendered correctly. Is there something I should be doing differently?

**Comment by liZe** [comment]
Thanks for this bug report!

`alignment-baseline="hanging"` is not supported in CairoSVG (more examples and related tests in #113), but to be honest it looks weird in your example: this value is mainly useful to align some Indic scripts. Using `"top"` looks like a good solution (if you can modify this file, of course).

**Comment by amir20** [comment]
Thanks @liZe. I have full control of the SVG file. Honestly, I am just trying to do a simple project and convert SVG to PNG. As long as the two are "similar" I am OK with it. 

I tried doing `alignment-baseline="top"` and it looks like same thing is happening again. Now instead the PNG drops the line lower. Here is what I mean:

SVG: 
<img width="220" alt="screen shot 2018-07-04 at 8 45 23 am" src="https://user-images.githubusercontent.com/260667/42286116-a2ca979e-7f66-11e8-916d-dd0ad0c11e11.png">


PNG: 
<img width="252" alt="screen shot 2018-07-04 at 8 45 51 am" src="https://user-images.githubusercontent.com/260667/42286133-ae71a43e-7f66-11e8-8adb-037b37000f38.png">

Looks like `y="XXX"` has a different translation on SVG vs PNG. What do you recommend I do to get similar results?

**Comment by liZe** [comment]
You're right, `text-alignment` is broken. I have to fix that!

**Comment by aziesemer** [comment]
> You're right, `text-alignment` is broken. I have to fix that!

 dominant-baseline is also broken. See #165

**Comment by aziesemer** [comment]
Comparison Chrome vs CairoSVG:

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline

<img width="585" alt="screen shot 2018-10-04 at 9 57 25 am" src="https://user-images.githubusercontent.com/11475314/46478937-f6e7d380-c7bb-11e8-9d7a-fe9adc249390.png">

**Comment by amir20** [comment]
Wohoo🎉

**Comment by aziesemer** [comment]
> Wohoo🎉

Don't get too excited... it is the same as alignment-baseline="top". But it is better than nothing though.

**Comment by amir20** [comment]
Oh... :) I'll take that over nothing.
