### ISSUE TITLE
Issue with svg/symbol viewbox other than 0 0 w h

### ISSUE THREAD

**Issue by aziesemer** [Kozea/CairoSVG#197]
Cairo svg doesn't support nested svg or symbol elements with viewbox with x,y position other than 0,0

See the example below:
[floor.svg.txt](https://github.com/Kozea/CairoSVG/files/2250823/floor.svg.txt)

Or this one, simpler:
[floor2.svg.txt](https://github.com/Kozea/CairoSVG/files/2250893/floor2.svg.txt)

<img width="574" alt="cairosvg_viewbox_issue" src="https://user-images.githubusercontent.com/11475314/43543409-e712071e-959d-11e8-8060-3de8427648ea.png">

**Comment by aziesemer** [comment]
These changes to svg.py fixed the issue for me:

```
def svg(surface, node):
   ...
    surface.context.translate(*surface.context.get_current_point())
    surface.context.translate(-rect_x, -rect_y)
    if node.get('overflow', 'hidden') != 'visible':
        surface.context.rectangle(rect_x, rect_y, rect_width, rect_height)
        surface.context.clip()
   ...
```

**Comment by liZe** [comment]
Thanks a lot for the issue and the fix!

**Comment by aziesemer** [comment]
@liZe Consider adding one of the examples above to the test set of cairosvg. None of the current svgs have view box with pos != (0,0)
