### ISSUE TITLE
Support to multi pages PDF

### ISSUE THREAD

**Issue by aziesemer** [Kozea/CairoSVG#200]
I added a pull request #199 that implements this functionality.

**Comment by aziesemer** [comment]
I found an issue, not related with  multi pages support, but with an optimization that I made together.

The Tree objects are being modified inside the converter. If I convert the same Tree object twice (i.e. to convert first to PDF and then to PNG), some elements appear in an incorrect position (svg/symbol instances) in the second call.

**Comment by liZe** [comment]
Thanks a lot for this issue and for the pull request.

I have taken some time to answer this issue, but I have to admit that I'm not really fond of multi-page support.

CairoSVG used to have this feature (and it had even been created for that, true story). It has created many problems and I had to find a solution… So, here is my solution:
- When I have only SVG files and just want to concatenate them, I use GhostScript. It's fast and give endless possibilities about pages order, scale, compression…
- When I want more complex layout, I put SVG files into HTML files and use [WeasyPrint](https://weasyprint.org/).

Would these solutions be OK for your needs?

**Comment by aziesemer** [comment]
I noticed that you had this functionality as a hack in the SVG standard in 2015. But I think that the solution in my pull request is more elegant and also doesn't brake CairoSVG interface.
However, I'd remove from my code the support to the tree_obj as a parameter since it can't be re-used (not sure why yet).

**Comment by liZe** [comment]
> I noticed that you had this functionality as a hack in the SVG standard in 2015. But I think that the solution in my pull request is more elegant and also doesn't brake current CairoSVG's interface.

You're right.



> I tried to avoid GS since the changes in CairoSVG where minimal. Actually I didn't change anything in CairoSVG's code since python allows you to override existing methods by injecting code from the caller module. GS is also pretty big.

I really appreciate your work, but I'm frightened by the idea and not very convinced by the implementation, namely:

- duplicating a lot of variable initializations in `addPage` is a bad idea,
- giving `parent_width` and `parent_height`  to `addPage` is a bit strange, it looks like a hack from the API point of view,
- allowing lists (why not tuples, why not other iterable objects?) for `bytestring` and other equivalent parameters is confusing,
- a `bytestring` parameter allowing a list of bytestrings is confusing too…

But I won't let you down :smile:!

I've tried to achieve what you want with the current API, and it is actually possible with a very little amount of code. Here is an example:

```python
import cairocffi
from cairosvg.parser import Tree
from cairosvg.surface import PDFSurface

def convert_list(urls, write_to, dpi=96):
    surface = cairocffi.PDFSurface(write_to, 1, 1)
    context = cairocffi.Context(surface)
    for url in urls:
        image_surface = PDFSurface(Tree(url=url), None, dpi)
        surface.set_size(image_surface.width, image_surface.height)
        context.set_source_surface(image_surface.cairo, 0, 0)
        context.paint()
        surface.show_page()
    surface.finish()

convert_list(['/tmp/file1.svg', '/tmp/file2.svg'], '/tmp/out.pdf')
```

You can of course adapt this sample to your needs. I hope that it will be enough for you to avoid GS.

**Comment by aziesemer** [comment]
I'm not a Python expert (I'm a c++ developer), so I just wanted to test the idea and make it work. So, you are absolutely right! :)

Thanks for the code. I'll try it later.

**Comment by liZe** [comment]
Closing this issue, as the code above should be enough for most cases.

**Comment by petr-vysotskiy** [comment]
Hi @liZe,

Sorry to bother you and thanks for the code above. I've noticed an issue in the output the code creates. Output PDF gets pixelated when I zoom it in. It feels like the image gets rasterized while being painted to context. Same SVG works just fine with command line version of CairoSVG. I'd appreciate if you can help me to fix that.

**Comment by petr-vysotskiy** [comment]
As an answer to my question above. Folks on internet are suggesting to use RecordingSurface in order to prevent rasterization. Here is quick and dirty solution:
`
import cairocffi
from cairosvg.parser import Tree
from cairosvg.surface import PDFSurface

class RecordingPDFSurface(PDFSurface):
    surface_class = cairocffi.RecordingSurface

    def _create_surface(self, width, height):
        cairo_surface = cairocffi.RecordingSurface(cairocffi.CONTENT_COLOR_ALPHA, (0, 0, width, height))
        return cairo_surface, width, height  

def convert_list(urls, write_to, dpi=72):
    surface = cairocffi.PDFSurface(write_to, 1, 1)
    context = cairocffi.Context(surface)
    for i, url in enumerate(urls, start=0):
        image_surface = RecordingPDFSurface(Tree(url=url), None, dpi)
        surface.set_size(image_surface.width, image_surface.height)
        context.set_source_surface(image_surface.cairo, 0, 0)
        context.paint()
        surface.show_page()
    surface.finish()

convert_list(['/tmp/file1.svg', '/tmp/file2.svg'], '/tmp/out.pdf')
`

**Comment by alexisdal** [comment]
does work. but the display is ugly. big ugly pixels and broken font. and yes I did try to incraese dpi. 
I have vector graphics containing barcode for small labels => a complete nogo :(

**Comment by ideogram** [comment]
I don't know if it is _comme il faut_ to ask a question in the comments of an issue, but I'll try anyway.

Thanks, @liZe  and @petr-vysotskiy petr-vysotskiy for your scripts, they work beautifully.

I try to avoid writing to temporary files because I want to my program to stay away from the file system as much as possible. I _succeeded_ in doing so by using a `io.BytesIO()` as an "in-memory-file" in combination with the sample script above.

However, I want to go further and It strikes me that functions like `svg2png` can return a bytestring instead of a file. I also notice in the docstring comment of `cairosvg.surface.Surface.__init__ ` :

>         The rendered content is written to ``output`` which can be a filename,
>         a file-like object, ``None`` (render in memory but do not write
>         anything) or the built-in ``bytes`` as a marker.

But I can't figure out the rest: is it possible to use the sample from @petr-vysotskiy in such a way that we obtain a bytestring straight away without the need of a file-like object? This would make the code even cleaner. 

Thanks in advance!

**Comment by liZe** [comment]
Hi @ideogram!

I don’t remember why `bytes` is allowed here, but as far as I can understand the implementation, the current code doesn’t allow this.

Cairo only allows filenames and streams as output, it can’t directly return a bytestring. So, even if some of CairoSVG’s functions are able to return bytestrings, it will always be based on `BytesIO` (as in [CairoCFFI’s `write_to_png`](https://github.com/Kozea/cairocffi/blob/cb237a5a6b242f5a53ace08568e08cc8cea20e9c/cairocffi/surfaces.py#L654-L656) or in [CairoSVG’s `convert`](https://github.com/Kozea/CairoSVG/blob/49c53b3a1d59d8ba1236095505e6ffb70f9ddfcb/cairosvg/surface.py#L131)).

So, we should find why `bytes` is said to be allowed in the docstring, and either fix the docstring or the code. Anyone interested in diving into the git commits history?

**Comment by ideogram** [comment]
Hello @liZe 

Thanks for the answer. If CairoCFFI and CairoSVG already use bytestrings, than I am in good company and keep my code like it is. Thanks a lot!
