### ISSUE TITLE
Geo PDF

### ISSUE THREAD

**Issue by mlgoff59** [Kozea/CairoSVG#201]
Can this library produce a GEO PDF?

[https://en.wikipedia.org/wiki/Geospatial_PDF](url)

**Comment by mlgoff59** [comment]
I was hoping to do it programmatically.  I haven't found any tools that support creating Geospatial PDFs.

**Comment by liZe** [comment]
> I was hoping to do it programmatically. I haven't found any tools that support creating Geospatial PDFs.

I understand. Unfortunately, as cairo (the library used to generate PDF files) doesn't support Geospatial PDFs, it's almost impossible to easily add this feature in CairoSVG.

**Comment by mlgoff59** [comment]
I was afraid that would be the case, but had to ask anyway.  Thank you!

**Comment by mlgoff59** [comment]
Martin Goff
mlgoff_59@yahoo.com
KK4EBS

"When you choose to see the good in people, most often they will strive to find the good within themselves. So whenever possible, choose to see the good in others."

-- Author anonymous


 “Success is not final, failure is not fatal: it is the courage to continue that counts.” - Winston Churchill

On Tuesday, August 21, 2018, 8:47 AM, Guillaume Ayoub <notifications@github.com> wrote:



I was hoping to do it programmatically. I haven't found any tools that support creating Geospatial PDFs.


I understand. Unfortunately, as cairo (the library used to generate PDF files) doesn't support Geospatial PDFs, it's almost impossible to easily add this feature in CairoSVG.
