### ISSUE TITLE
Text on paths is not rendered correctly in PNG and PDF

### ISSUE THREAD

**Issue by kvolleberg** [Kozea/CairoSVG#203]
I have a SVG [see here](https://codepen.io/anon/pen/EeVBKQ) with text in a circular shape. The SVG is shown correctly in Chrome and FF.

I want to convert this shape to PDF and/or PNG, but the text is shown in the middle of the image, instead of following the blue outer circles. 
![output](https://user-images.githubusercontent.com/6346972/44592505-06d5c600-a7c1-11e8-82d6-1f8203c30e26.png)

I have found an issue (#144 ) that somewhat describes the same problem. However, I use the latest version (2.1.3) with Python 3.6 (x64), so including the bugfix. Maybe something else is wrong?

**Comment by liZe** [comment]
There are many problems:
1. As your path is not in a `defs` tag, it's cannot be referenced. It's bug #189 and it could be fixed by #192, but I have to clean it before merging.
2. Your file misses the `xlink` namespace for `href` attributes, browsers seem OK with that but CairoSVG isn't. You should use `xlink:href` instead of just `href` in your SVG file.
3. The text is not at the same place in browsers and in CairoSVG. I have to check what's wrong (probably a bug in CairoSVG).

**Comment by kvolleberg** [comment]
I have struggled with the file myself before I found your comment. I have validated the SVG with the W3C svg validator and your 2nd issue was shown as an error there. I have fixed this.

I have implemented your fix #192 in my local CairoSVG. Now, the text is plotted on the paths, but I think problem 3 comes into play here as the text is plotted at different locations. Hope you can find out what the issue is. I will dive into it myself as well, but I am pretty new to python-coding with SVG and CairoSVG so it may be without success.

**Comment by kvolleberg** [comment]
I have managed to create a PNG with the text following the paths correctly:
![example](https://user-images.githubusercontent.com/6346972/44745966-758c8980-ab09-11e8-973d-d888a4cd4e8d.png)

[Here is the original SVG](https://codepen.io/anon/pen/yxJdoy)

I have fixed the problems mentioned above:

> As your path is not in a defs tag, it's cannot be referenced. It's bug #189 and it could be fixed by #192, but I have to clean it before merging.
   
I have implemented the code from url.py and surface.py from fix #192 

> Your file misses the xlink namespace for href attributes, browsers seem OK with that but CairoSVG isn't. You should use xlink:href instead of just href in your SVG file.

I have added the xlink in my own script.

>  The text is not at the same place in browsers and in CairoSVG. I have to check what's wrong (probably a bug in CairoSVG).

I have changed one line in text.py
WAS:
line 162: `surface.text_path_width += start_offset - x_align`

IS:
line 162: `surface.text_path_width = start_offset - x_align`

The change from '+=' to ' = ' solved my problem. I don't know if this breaks other issues, but this might give you a clue where to find the problem and how to solve it.

Cheers, Koen

**Comment by liZe** [comment]
> The change from '+=' to ' = ' solved my problem. I don't know if this breaks other issues, but this might give you a clue where to find the problem and how to solve it.

That was really, really useful, thanks! The bug has been fixed in 90def7a, I'll release a new version soon.
