### ISSUE TITLE
Doesn't work when image urls inside svg contain spaces

### ISSUE THREAD

**Issue by 4levels** [Kozea/CairoSVG#226]
As soon as an image inside a svg document contains a space (be it litteral or encoded as %20), this library crashes.  Some tracing shows that in image.py on line 43, the returned url is `None`, yet the next line tries to fetch this.  The fix is as simple as adding a basic check for validity of the url (eg. `if url is not None`) but given the long history of ongoing issues with spaces I'm not even surprised anymore.

see eg #118 or https://github.com/Kozea/WeasyPrint/issues/645

Any feedback on how to resolve this would be great!  I've been reading through a lot of old issues about custom url fetchers and what more but none seem to address this simple input validation issue.

**Comment by liZe** [comment]
It's fixed in version 2.3.0.
