### ISSUE TITLE
incorrect parse URL for mask/filter on Windows OS

### ISSUE THREAD

**Issue by zizizuq** [Kozea/CairoSVG#227]
I tried to convert a lot of svg with mask. But nothing work in windows platform. For example this svg:
```
<svg xmlns="http://www.w3.org/2000/svg" width="99" height="20">
    <mask id="a">
        <rect width="80" height="20" rx="3" fill="#fff"/>
    </mask>
    <g mask="url(#a)">
        <path fill="#555" d="M0 0h63v20H0z"/>
        <path fill="#a4a61d" d="M63 0h36v20H63z"/>
    </g>
    <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
        <text x="31.5" y="15" fill="#010101" fill-opacity=".3">coverage</text>
        <text x="31.5" y="14">coveragse</text>
        <text x="80" y="15" fill="#010101" fill-opacity=".3">61%</text>
        <text x="80" y="14">61%</text>
    </g>
</svg>
```

After debug I found that mask url is parsing incorrect. Why you do additional conversation for (os.name == 'nt')?

![image](https://user-images.githubusercontent.com/45353847/50628197-acebc680-0f3f-11e9-9503-2920787165af.png)

![image](https://user-images.githubusercontent.com/45353847/50628264-094ee600-0f40-11e9-9ff2-6a37d5d5856b.png)

**Comment by liZe** [comment]
It's probably fixed since version 2.3.1 (see #236 and 90f1e94).
