### ISSUE TITLE
Python 3.7 breaks CSS

### ISSUE THREAD

**Issue by luc-x41** [Kozea/CairoSVG#228]
`example.svg`:

    <?xml version="1.0"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg xmlns="http://www.w3.org/2000/svg" width="526" height="233">
      <style type="text/css">
        .bg {
          fill: rgba(255, 255, 255, 1);
        }
      </style>
      <rect class="bg" x="13" y="14" width="500" height="200" rx="50" ry="100" stroke="blue" stroke-width="10" />
    </svg>

`convert.py`:

    import cairosvg
    cairosvg.svg2png(bytestring=open('example.svg', 'rb').read(), write_to='example.png')

`$ python3.6 convert.py` gives the expected result (or at least, I have come to expect this):

![white background](https://lgms.nl/tmp/cairosvg-example-36.png)

`$ python3.7 convert.py`:

![white background](https://lgms.nl/tmp/cairosvg-example-37.png)

The same happens with `svg2pdf`.

**Comment by luc-x41** [comment]
It seems to be helped by installing tinycss. After running `apt install python3-tinycss` or `pip3 install tinycss`, the issue is resolved.

**Comment by liZe** [comment]
> It seems to be helped by installing tinycss. After running `apt install python3-tinycss` or `pip3 install tinycss`, the issue is resolved.

Old versions of CairoSVG optionally depend on tinycss, but recent versions have a mandatory dependency to tinycss2. You should upgrade CairoSVG :smile:.

**Comment by liZe** [comment]
`pip3 show` shows the currently installed version, not [the available versions online](https://pypi.org/project/CairoSVG/).

`apt-cache` shows the version provided by your Linux distribution. So yes, the version provided by your distribution is outdated.

If you want to use the latest version, you should uninstall the version provided by the distribution and install using `pip3 install`.

**Comment by luc-x41** [comment]
Oh `pip3 show` shows the version of whatever it finds on your system instead of the version available on pip, I didn't know that. That explains, thanks! Sorry for the bogus report.
