### ISSUE TITLE
DPI doesn't work with group transform when exporting PNGs

### ISSUE THREAD

**Issue by aziesemer** [Kozea/CairoSVG#229]
It only happens if DPI is different than the default (96) value and in PNGs only (PDFs are fine):

DPI = 96 (default)
![test](https://user-images.githubusercontent.com/11475314/51479620-c15ff980-1d5c-11e9-9201-7731bac56197.png)

DPI = 140
![test2](https://user-images.githubusercontent.com/11475314/51479621-c329bd00-1d5c-11e9-933b-3f5a5a8d50be.png)

Original SVG:
[floor-2.svg.txt](https://github.com/Kozea/CairoSVG/files/3525375/floor-2.svg.txt)

It seems to be related to the SVG viewBox not starting at position 0,0 or the group transformation in this line:
<g transform="translate(490.20115 274.4861875)  scale(1.1 1.1) translate(-490.20115 -274.4861875)">

**Comment by aziesemer** [comment]
The

**Comment by aziesemer** [comment]
Was it fixed in 2.4.0?

**Comment by liZe** [comment]
> Original SVG:
> [floor-2.svg.txt](https://github.com/PlanitarInc/svg2pngdf/files/2779221/floor-2.svg.txt)

The link is broken.

**Comment by aziesemer** [comment]
> > Original SVG:
> > [floor-2.svg.txt](https://github.com/PlanitarInc/svg2pngdf/files/2779221/floor-2.svg.txt)
> 
> The link is broken.

It should be fixed now... Sorry for that.

**Comment by liZe** [comment]
Your SVG file mixes SVG user units (with no unit identifier, for example in transforms or paths) and absolute units (millimeters), so modifying the DPI will change the rendering. It's not a bug, it's a feature :smile:.

As the specification says:
> Note that use of px units or any other absolute unit identifiers can cause inconsistent visual results on different viewing environments since the size of "1px" may map to a different number of user units on different systems; thus, absolute units identifiers are only recommended for the ‘width’ and the ‘height’ on and situations where the content contains no transformations and it is desirable to specify values relative to the device pixel grid or to a particular real world unit size.

You should not use absolute units, especially if you want to play with the `dpi` argument.

If you want to scale the generated image, use the `scale` argument.

**Comment by liZe** [comment]
@aziesemer Can I close this issue?

**Comment by aziesemer** [comment]
I will. Thanks!
