### ISSUE TITLE
Recursive image fetch can lead to DOS

### ISSUE THREAD

**Issue by akhil-reni** [Kozea/CairoSVG#246]
I was working on a security project for one of my customer who is using Weezyprint. We realized that Weezyprint uses CairoSVG to handle SVG images.

Digging in deep we found that there is a flaw in how images are handled. For example, if an SVG image has an image with src http://example.com/a.svg and a.svg has an image with src http://example.com/a.svg again, it will lead to python RecursionError.

**To reproduce**

- Save the below code as a.svg

```
<svg width="200" height="200"
  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">       
  <image xlink:href="http://139.59.92.72/a.svg" height="200" width="200"/>
</svg>
```

- Run python3 -m cairosvg a.svg -o a.png

The following error will appear

```
RecursionError: maximum recursion depth exceeded while calling a Python object.
```

Tested on:
cairosvg==2.4.0
Ubuntu 18.04.2

**Comment by liZe** [comment]
Thank you! It's actually a duplicate of #19.
