### ISSUE TITLE
Scale parameter appears to be broken in 2.4.1

### ISSUE THREAD

**Issue by abey79** [Kozea/CairoSVG#248]
I'm still seeing issues with upscaling on 2.4.1. Version 2.4.0 doesn't seem to be affected by this.

I'm running these commands:

```bash
$ cairosvg -s 1 -o test1.png svgwrite-example.svg
$ cairosvg -s 2 -o test2.png svgwrite-example.svg
```

Both PNGs have the good size (500x500 and 1000x1000, source SVG is 500x500), but test2.png contains a 500x500 output in the top left corner, the rest being transparent. I tried various combinations with output height/width to no avail.

Here is the SVG file I'm testing with: [svgwrite-example.svg.zip](https://github.com/Kozea/CairoSVG/files/3587635/svgwrite-example.svg.zip)

**Comment by liZe** [comment]
I'll try to release soon a new version of CairoSVG with this issue fixed. Please ping me if it's not done at the end of the week :wink:.

**Comment by abey79** [comment]
Merci ;)
