### ISSUE TITLE
Opacity not applied to gradients fills

### ISSUE THREAD

**Issue by guidotheelen** [Kozea/CairoSVG#263]
When converting svg to png, the opacity is not being applied to elements with a gradient fill.

Example:
```
<linearGradient gradientUnits="userSpaceOnUse" id="a" x1="1" x2="2" y1="3" y2="4">
	<stop offset="0" stop-color="#fff" stop-opacity="0"/>
	<stop offset=".9151" stop-color="#090909" stop-opacity=".9151"/>
	<stop offset="1"/>
</linearGradient>
	
<path d="m124 107.2c-1.85 1.12-3.66 2.06-5.43 2.8" fill="url(#a)" opacity=".3"/>
```
The `opacity=".3"` is not being used. 

Example Image:

Needs to be:
![emoji_u1f3f3_200d_1f308](https://user-images.githubusercontent.com/9211107/76299219-fb6ec080-62ba-11ea-96b1-fe3c5eca3e10.png)

Becomes: 
![emoji_u1f3f3_200d_1f308](https://user-images.githubusercontent.com/9211107/76299240-06c1ec00-62bb-11ea-81bd-62cb2cf9eb5b.png)

Or am I missing something?

**Comment by guidotheelen** [comment]
Link to the graphic itself:
https://github.com/googlefonts/noto-emoji/blob/master/svg/emoji_u1f3f3_200d_1f308.svg

**Comment by guidotheelen** [comment]
I just found a workaround, if I wrap the path with a group that has the same opacity. It works fine.

Instead of:
`<path d="bla bla" fill="url(#a)" opacity=".3"/>`

I used:
`<g opacity=".3"><path d="bla bla" fill="url(#a)"/></g>`

**Comment by aziesemer** [comment]
Have you tried to fix CairoSVG code? Sometimes it is easier to fix than creating a workaround.

**Comment by liZe** [comment]
@guidotheelen Thanks a lot for the bug report (with a very useful sample).

**Comment by RoelN** [comment]
Thanks @liZe @guidotheelen! \o/

**Comment by guidotheelen** [comment]
Good job @liZe, thanks a lot! 🐎
