### ISSUE TITLE
Make orient="auto-start-reverse" work

### ISSUE THREAD

**Issue by sarahriethmueller** [Kozea/CairoSVG#269]
Hi, svg2png raises a ValueError "could not convert string to float: 'auto-start-reverse" for me.
it seems like you don't check for auto-start-reverse. is this feature supposed to be supported in the current version of CairoSVG?

**Comment by liZe** [comment]
Hello!

[`auto-start-reverse`](https://svgwg.org/svg2-draft/painting.html#OrientAttribute) has been added by the version 2 of the SVG specification, that’s why it’s not handled yet.

If anyone is interested, that’s probably a good issue to become a contributor :wink:.
