### ISSUE TITLE
Embedded jpegs not obeying EXIF orientations

### ISSUE THREAD

**Issue by jlugao** [Kozea/CairoSVG#278]
Hi, I have an application where customers can send pictures from their phones to generate a postcard. The mobile app sends an svg with an jpg image embedded, the problem is that on the newer iphones the image's default orientation is landscape and whenever a picture is taken in portrait mode they stick an orientation on EXIF metadata such as:

EXIF
Color Space	Uncalibrated
Exif Image Size	4,032 × 3,024
Orientation	Rotate 90 CW

The result is that the image appears on the wrong orientation when I render the pdf using weasyprint. But I believe that this is actually from CairoSVG no handling EXIF for embedded images.

I'll probably make a fix on my application extracting the image, decoding, rotating, encoding and embedding again. Since I'll be going to the trouble, is it possible to fix this directly in Cairo? if so, can you point me to where in the code I should take a look in order to create a PR with the fix?

**Comment by liZe** [comment]
Hello, and thank you for this bug report.

> But I believe that this is actually from CairoSVG no handling EXIF for embedded images.

You’re right.

> if so, can you point me to where in the code I should take a look in order to create a PR with the fix?

That would be nice, thank you.

Images are transformed into PNG files, that’s where the EXIF information is probably lost. The conversion is done by [Pillow](https://python-pillow.org/) in [`image.py`](https://github.com/Kozea/CairoSVG/blob/93e442afa0e200db5773ad1de9d74add9e3f3272/cairosvg/image.py#L94). I’m pretty sure that Pillow gives a way to get EXIF metadata, so it should be possible to get and apply the rotation in a clean way.
