### ISSUE TITLE
Passed text SVG cropped in output file

### ISSUE THREAD

**Issue by Rolandisimo** [Kozea/CairoSVG#288]
I am trying to render a simple text SVG with cairo 2.4.2.
The result is that the last letter "n" is removed from the final SVG completely. Changing output_width|height and/or parent_width|height does not help.

**Python version:** 3.5.9

**Code:**
```
for item in items:
  for child in children:
    cairosvg.svg2png(
      bytestring=image["src"], # I tried creating a file and using url as well 
      write_to="{}".format(image_name),
      output_width=image["width"],
      output_height=image["height"],
    )
```

**Requirements.txt:**
```
setuptools==40.0.0
lxml==4.1.1
pymongo==3.6.0
twisted==17.9.0
txmongo==18.0.0
requests==2.18.4
python-dateutil==2.7.3
prometheus-client==0.3.0
mysql-connector==2.1.7
psutil==5.7.2
Pillow-simd==6.0.0.post0
cffi==1.14.2
cairocffi==1.1.0
cairosvg==2.4.2
```

**Source:** https://www.w3schools.com/code/tryit.asp?filename=GHU21C7GRF0W
![Screenshot 2020-08-17 at 14 20 48](https://user-images.githubusercontent.com/9778368/90390919-e6316580-e094-11ea-9cf7-fecf29074c04.png)
**Result:** https://www.w3schools.com/code/tryit.asp?filename=GHU1UNMTT9A3
![Screenshot 2020-08-17 at 14 20 59](https://user-images.githubusercontent.com/9778368/90390924-e7629280-e094-11ea-897b-5ba1601bb84d.png)

What could be the reason for this? I tested out in a separate venv and there was no issue.

**UPDATE:**
I noticed that the issue stems from the output_width and output_height ratio. The cropped result happens with                     
- `output_width=1041.140625,`
- `output_height=233.625,`

However, if I make it 
- `output_width=1041.140625,`
- `output_height=200,`

I see 2/3 of the "n" character rendered

Testing with Python 3.8 the issue was not present. In fact, I could put any values in or remove output_width|height and the full svg would still be rendered.

**Comment by liZe** [comment]
Hello!

The problem you have is that the font used in the source is not available when you render it using CairoSVG. The characters of the fallback font are larger, and thus the "n" doesn’t fit.

Make sure to have the font installed (it’s Roboto) on the system you use to render your image.

**Comment by Rolandisimo** [comment]
You're awesome! Thanks! That indeed fixed the issue
