### ISSUE TITLE
Set DPI in PNG images

### ISSUE THREAD

**Issue by jwcarr** [Kozea/CairoSVG#290]
If `input.svg` is a 1 inch square like this:

```
<svg width="1in" height="1in" viewBox="0 0 100 100">
	<rect width="100" height="100" fill="black"/>
</svg>
```

and then I convert to a 300dpi PNG like this

```
cairosvg.svg2png(url="input.svg", write_to="output.png", dpi=300)
```

then `output.png` will have dimensions of 300x300px, which is correct. However, the DPI metadata is not set properly, so when I open `output.png` in graphics software, the software assumes the default DPI of 72, which would imply that the image is meant to have a physical width of 4.167 inches.

It would be nice if CairoSVG would also set the DPI when converting to PNG. Currently, CairoSVG only seems to use the `dpi` parameter to figure out the pixel dimensions of the image.

A workaround I came up with is to pass the output through PIL, setting the DPI:

```
from PIL import Image
with Image.open("output.png") as im:
	im.save("output.png", dpi=(300, 300))
```

I had a look through the CairoSVG source code and I couldn't figure out a way to implement this – it seems like it could be a constraint imposed by Cairo itself, which possibly doesn't allow the DPI metadata to be set?

**Comment by liZe** [comment]
Hello!

> I had a look through the CairoSVG source code and I couldn't figure out a way to implement this – it seems like it could be a constraint imposed by Cairo itself, which possibly doesn't allow the DPI metadata to be set?

Right. Cairo generates the PNG file but doesn’t include metadata. The only way we have to fix that is to change the file afterwards, just like you did with the PIL.

**Comment by jwcarr** [comment]
Thanks for confirming my suspicions!
