### ISSUE TITLE
Encapsulated postscript

### ISSUE THREAD

**Issue by jwcarr** [Kozea/CairoSVG#294]
If I convert [this SVG file](https://joncarr.net/t/input.svg) to EPS by doing:

```shell
cairosvg -f ps -o output.eps input.svg
```

The resulting file appears to be rotated by 90º in Apple Preview, but is correctly oriented in Affinity Designer:

![](https://joncarr.net/t/screenshot.png)

This bug seems to be related to whether or not the EPS file is properly encapsulated by Cairo. In Cairo, you produce encapsulated postscript by calling `set_eps(True)` on a `PSSurface` (https://cairocffi.readthedocs.io/en/latest/api.html?highlight=set_eps#cairocffi.PSSurface.set_eps). If I change CairoSVG so that it produces EPS output:

```python
# surface.py
class PSSurface(Surface):
    """A surface that writes in PostScript format."""
    surface_class = cairo.PSSurface

    ##### NEW CODE #####
    def _create_surface(self, width, height):
        cairo_surface = self.surface_class(self.output, width, height)
        cairo_surface.set_eps(True)
        return cairo_surface, width, height
    ##### NEW CODE #####
```

then Apple Preview renders the resulting EPS file correctly. So it seems that if you create a fake EPS file that is actually just PS, the Mac renderer is sometimes confused about the orientation for some reason.

In any case, regardless of this bug, I though it might be worth discussing whether CairoSVG should actually produce EPS by default. I'm no expert, but EPS is widely used in the publishing industry as the standard vector graphics format, and I believe that EPS is more appropriate if you intend to make a self-contained vector graphics file rather than a multipage document, so it feels like EPS would be a more natural choice for typical use-cases of CairoSVG.

Alternatively, perhaps it would make sense to offer the user the option to output to EPS by creating a new `svg2eps` function. This would keep CairoSVG's current behavior consistent and would basically just involve adding an `EPSSurface` class with a custom `_create_surface()` like the above. I would be happy to go ahead and work on this, but I though it might be worth discussing potential issues first.

**Comment by liZe** [comment]
Hello!

> Alternatively, perhaps it would make sense to offer the user the option to output to EPS by creating a new `svg2eps` function. This would keep CairoSVG's current behavior consistent and would basically just involve adding an `EPSSurface` class with a custom `_create_surface()` like the above. I would be happy to go ahead and work on this, but I though it might be worth discussing potential issues first.

It looks like a very good idea. You can open a PR if you want/can, or wait for the feature to be added as soon as I take some time.

**Comment by jwcarr** [comment]
Awesome! That was surprisingly straight-forward. Any idea when this might make it into a release?

**Comment by liZe** [comment]
> Any idea when this might make it into a release?

As soon as [CourtBouillon](https://courtbouillon.org) is officially launched :wink:.
