### ISSUE TITLE
Image corruption in png

### ISSUE THREAD

**Issue by kolonuk** [Kozea/CairoSVG#304]
Trying to do a conversion of an SVG file to a png, and there seems to be some corruption/artifacting going on in the resulting png file.  The attached zip has both the original SVG and the png file.

![E28107-02122030668](https://user-images.githubusercontent.com/5969835/102368200-813e3b80-3fb2-11eb-83c0-e94592219b49.png)

The SVG is produced in Adobe Illustrator 11.  My version of Cairo is 1.0.20 (I think this is Ubuntu's default version), and it's running on Ubuntu 18.04.4, all up to date.  I've just updated Cairosvg to 2.5.0 (via pip3) and still broken.

[corruption.zip](https://github.com/Kozea/CairoSVG/files/5703611/corruption.zip)

**Comment by liZe** [comment]
Hello!

That was a dirty bug, it’s fixed now. Thanks for your bug report!

**Comment by liZe** [comment]
![E28107-02122030668](https://user-images.githubusercontent.com/952243/102936912-591a7500-44a9-11eb-9f19-a45e7f10b915.png)

**Comment by kolonuk** [comment]
Thanks, I've yet to test it, but any idea when it will make it to the official branch?

**Comment by liZe** [comment]
> Thanks, I've yet to test it, but any idea when it will make it to the official branch?

It’s already in version 2.5.1! 😉

**Comment by kolonuk** [comment]
Thanks!
