### ISSUE TITLE
publish 2.4.3 with for fix for GHSA-hq37-853p-g5cf ?

### ISSUE THREAD

**Issue by FelixSchwarz** [Kozea/CairoSVG#308]
Seems like the fix for GHSA-hq37-853p-g5cf also applies to 2.4.x. We are shipping CairoSVG 2.4.2 in Fedora 32+33 so I would like to fix that version as well. It seems as if commit 063185b60588a41d4df661ad70f9f7b699901abc is almost trivial to backport.

Would you mind to check if commit 063185b60588a41d4df661ad70f9f7b699901abc would fix the security issue also for CairoSVG 2.4.2? ["backport" for CairoSVG 2.4.2](https://github.com/Kozea/CairoSVG/files/5778670/python-cairosvg-fix-GHSA-hq37-853p-g5cf.txt)

Even if you don't want to publish a new version we could carry the patch on top of 2.4.2 for Fedora but I'd like to get some confirmation that the patch is actually working also for 2.4.2 (maybe I'm overlooking something important?).

**Comment by liZe** [comment]
> Would you mind to check if commit [063185b](https://github.com/Kozea/CairoSVG/commit/063185b60588a41d4df661ad70f9f7b699901abc) would fix the security issue also for CairoSVG 2.4.2? ["backport" for CairoSVG 2.4.2](https://github.com/Kozea/CairoSVG/files/5778670/python-cairosvg-fix-GHSA-hq37-853p-g5cf.txt)

It does. You can backport the patch to 2.4.2, I probably won’t release other versions than 2.5.1.

**Comment by FelixSchwarz** [comment]
Thank you. I just kicked off builds for Fedora with the additional patch.
