### ISSUE TITLE
Blurred images caused by mask usage

### ISSUE THREAD

**Issue by kubasaw** [Kozea/CairoSVG#311]
Hi, 
For a few days, I'm facing with the issue of generating PNG from SVG containing ```mask``` element. The minimal example of problematic SVG is shown below:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 30" version="1.1">
    <defs>
        <mask id="test_mask" fill="#fff">
            <circle cx="15" cy="15" r="15" />
        </mask>
    </defs>
    <rect width="30" height="30" fill="#fff" />
    <rect width="30" height="30" mask="url(#test_mask)" fill="#00f" />
</svg>
```
Without an explicit dpi value set, the output image is blurred. After reducing the dpi, the picture becomes clearer, but the processing becomes much longer and requires much more memory. I'm using following Python code:
```
import cairosvg

def fcn(dpi):
    with open('test.svg', 'r') as svg:
        cairosvg.svg2png(
            file_obj=svg, write_to=f'dpi{dpi}.png', dpi=dpi, output_width=200)

fcn(2)
fcn(96)
```

and the results are following:
DPI=2
![dpi2.png](https://user-images.githubusercontent.com/13100091/106211081-586faf80-61c8-11eb-9d0c-43042c012061.png)

DPI=96
![dpi96.png](https://user-images.githubusercontent.com/13100091/106211091-5c9bcd00-61c8-11eb-95b0-8e72b0d47398.png)

After some investigation, I think the issue is caused by drawing mask on SVGSurface of relatively small size and rescaling it up afterwards here https://github.com/Kozea/CairoSVG/blob/44c5d42f96be879fc4e21775e51300bd3ad0093e/cairosvg/defs.py#L147-L154
but I don't have any idea how can I fix this problem in some elegant way. In the listed example it shouldn't be so complicated to move circle definition out of mask, but when more elements are included in the mask and fill is not solid (what is my real case), I have not found any drop-in replacement in the SVG syntax.

Do you have any tips, how can I try to fix it?

**Comment by liZe** [comment]
> Do you have any tips, how can I try to fix it?

That’s a good question. I think that scaling shouldn’t change anything theoretically, but sometimes Cairo rasterizes too early. 

Could you try to scale `mask_surface` (by the invert of the current scaling values) instead of scaling `surface`?

**Comment by kubasaw** [comment]
Hi @liZe,

I checked this hint and it seems to me that everything works fine. Unfortunately, I'm not able to do exhaustive tests to be sure if it resolves problem for more complicated svgs. 
I'm closing this issue as it doesn't seem to be directly related to cairosvg but rather to cairo itself.

Thank you for your help,
Kuba
