### ISSUE TITLE
SVG files to Multipage PDF

### ISSUE THREAD

**Issue by megazhuk** [Kozea/CairoSVG#312]
Hello frinds! ✌
Can **CairoSVG** render multipage PDF from many SVG files?
Or maybe there are function to join many PDFs to one?

**Comment by liZe** [comment]
Hello!

CairoSVG can’t render multipage PDFs anymore, but there are many ways to join PDFs with external tools. The easiest way I know is to use [Ghostscript](https://gist.github.com/brenopolanski/2ae13095ed7e865b60f5).

Have fun with CairoSVG!

**Comment by aziesemer** [comment]
@megazhuk I added support a few years ago, in a hackish way, but it never made to master:
https://github.com/Kozea/CairoSVG/pull/199

Lize also proposed a better way in https://github.com/Kozea/CairoSVG/issues/200 which may work better, perhaps.
