### ISSUE TITLE
SVG Marker size broken in 2.5.1

### ISSUE THREAD

**Issue by cduck** [Kozea/CairoSVG#316]
Thanks for making this great package.  I use it as a backend for my vector drawing library drawSvg.

After upgrading from 2.5.0 to 2.5.1, it appears that markers no longer render correctly (compared to various browser implementations).  For context, see this issue: https://github.com/cduck/drawSvg/issues/37.

**Comment by grewn0uille** [comment]
Hello!
Can you provide a svg sample with this problem please?

**Comment by cduck** [comment]
The SVG rendered by CairoSVG 2.5.0, Firefox, or Chrome:
![out](https://user-images.githubusercontent.com/2476062/110143962-b7c86d00-7dcf-11eb-8ae1-c90c5734a683.png)

The SVG rendered by CairoSVG 2.5.1:
![out-wrong](https://user-images.githubusercontent.com/2476062/110143970-bac35d80-7dcf-11eb-831b-884ba852a23f.png)

**Comment by cduck** [comment]
I found the likely cause of the issue.  Line 102 of [path.py](https://github.com/Kozea/CairoSVG/blob/2.5.1/cairosvg/path.py#L102) in the [published version of 2.5.1 on PyPI](https://pypi.org/project/CairoSVG/2.5.1/#files) is different than in tag 2.5.1 on GitHub.  It appears the bug was introduced in the process of publishing version 2.5.1 to PyPI.

- When I install from the GitHub source (with tag 2.5.1 checked out), I get the correct output (1st image in my comment above).
- When I install from the PyPI source (2.5.1), I get the wrong output (2nd image in my comment above).
- When I edit the PyPI source (uncomment line 102 of path.py so it matches the file in git), I now get the correct output (1st image).

**Comment by grewn0uille** [comment]
Thanks for your investigation! We just published a new release with the correct code.
