### ISSUE TITLE
Interesting bug: exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by pwichmann** [Kozea/CairoSVG#319]
First of all, many thanks for maintaining this open source project. Thank you!

I came across an interesting bug that has been driving me nuts for months. I am still unable to explain the phenomenon.

### TL;DR
A specific SVG can be converted to PNG in some target sizes but fails with `exit code 139 (interrupted by signal 11: SIGSEGV)` in some other target size. For some other unknown reason, this above error is not caught by my try / except clause and crashes the Python program.

Environment:

- Python 3.8
- cairosvg 2.5.2
- Ubuntu

### The SVG in question
Below is the SVG in question. Just a random SVG from the Web.

```XML
<?xml version='1.0' encoding='utf8'?>
<svg height="119.5" preserveaspectratio="xMinYMin meet" viewBox="0 0 401.2 119.5" width="401.2" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid meet">
<pattern height="354.844" id="progress" patternunits="userSpaceOnUse" width="79.36" x="0" y="0">
<rect fill="currentColor" height="100%" id="progressMove" stroke="none" width="100%" x="0" y="0" />
</pattern>
<g id="PAG">
<path class="st0" d="M17.3 85c.1-.5-.7-.9-2.5-1.5-1.8-.5-3.9-1-6.1-1.5-5.9-1.2-8.8-2.2-8.6-3 .3-.9 1.6-1.8 3.9-2.7 2.3-.9 5.6-2 10-3.2 4.4-1.4 6.7-2.1 7-2.3 1.7-.9 5-2.2 10.1-4 5.1-1.7 8.5-2.9 10.3-3.5L24.6 56 37.9 2.3h36.8c9.8 0 18 1.1 24.5 3.2s11.8 5.4 15.9 9.8c5.8 5.9 8.6 13.7 8.6 23.4 0 6.2-.9 12-2.7 17.5-.2.5.2.9.9 1.4.8.5 2 .9 3.6 1.5 1.7.5 2.8.9 3.4 1 2 .5 3.7 1 5.3 1.7 1.6.7 2.2 1.2 1.9 1.7-.5.8-2.4 1.6-5.8 2.4-3.4.8-5.5 1.3-6.2 1.5-7.1 1.5-11.1 2.7-11.8 3.6-.3.2-.7.3-1.1.5-.5.1-.8.2-1.1.2-1.4.3-4.9 1.1-10.7 2.3-5 .9-8.8 1.7-11.5 2.5-2.7.8-4.1 1.7-4.2 2.7-.3 1.5.1 2.6 1.2 3.3 1.1.7 2.3 1.2 3.4 1.6 1.1.4.9.8-.8 1.3-5.6 1.5-12 2.3-19.1 2.3H53.2l-8 31.8H8.6L17.3 85zm56.1-51.4h-6.8l-6.4 25.9h6.6c7.4 0 12.9-1.9 16.6-5.7 2.4-2.4 3.6-5.7 3.6-9.8 0-2.7-.9-5-2.7-6.8-2.3-2.4-5.9-3.6-10.9-3.6zM139.7 85.4l-10.9-5.7 20-8.4 19.5-7.3-10-7.3 34.5-54.1h35.9l7.7 54.1 15.7 7.3-13.6 7.3-13.6 8.4 15.7 5.7 4.8 34.1h-38.6l-1.8-15.7h-38l-9.5 15.7h-39.3l21.5-34.1zm63.2-9.1l-3-28.2-16.8 28.2h19.8zM275.8 83.2c-.2-.6-3.2-1.5-9.1-2.7-.9-.1-2.8-.6-5.6-1.2-2.8-.7-4.3-1.3-4.4-1.9-.2-.8.2-1.3 1-1.7.8-.4 2.4-.9 4.7-1.7 2.3-.6 5.1-1.7 8.6-3.2.1 0 .5-.1 1-.2s1.3-.5 2.4-1.1l4.3-1.6c9.1-2.7 13.6-4.6 13.6-5.7.1-.6-.7-1.2-2.6-1.9-1.9-.7-4-1.2-6.2-1.7-5.6-1.5-8.3-2.6-8.2-3.4 2.3-13.2 7.8-24.4 16.6-33.6 6.2-6.8 13.8-12.1 22.7-15.8 8.9-3.7 18.9-5.6 29.8-5.6 9.5 0 18.4 1.9 26.5 5.6C379 9.3 385 13.7 389 18.9l-22.3 24.3c-3-3-6.7-5.5-11-7.4-4.3-1.9-8.8-2.8-13.5-2.8-4.8 0-9.3.8-13.3 2.5s-7.5 4-10.3 7c-3 3.5-5.4 7.6-7 12.3-.2.8 2.6 1.9 8.2 3.4.6.2 1.5.4 2.7.8 1.2.4 2.5.9 4 1.5 1.4.6 2.1 1.1 1.9 1.6-.3.8-2.4 1.5-6.1 2.3-3.6.9-5.8 1.6-6.4 2-.3.3-1.2.8-2.7 1.5-1.5.7-2.5 1.2-3 1.5-1.8 1.1-4.5 2.3-8.2 3.6-2.1.8-4 1.5-5.7 2.3-1.7.8-2.4 1.4-2 2 .3.6 1.8 1.2 4.5 1.8 2.7.6 5.6 1.2 8.6 1.8 5.6.8 8.9 1.5 9.8 2.3 3.8 2.9 8.3 4.3 13.4 4.3 3.5 0 6.6-.6 9.3-1.8l3.4-12.3h-17.5l1.1-4.1 19.8-7.3-16.4-7 1.4-6.1H383l-1.6 6.1 19.8 7-23.6 7.3-20.2 8 16.6 5.9-6.1 23.9c-5.6 3.6-12 6.5-19.2 8.6-7.2 2.1-14.5 3.2-21.9 3.2-12 0-22.7-3-32.2-9-9.5-6-15.7-14.9-18.8-26.7z" fill="url(#progress)" stroke="#DDD" stroke-width="1" />
</g>
</svg>
```

### The code

```Python
def render_svg_and_return_bytes(svg_content_cleansed, width, height):

    result = None

    try:
        result = cairosvg.svg2png(bytestring=svg_content_cleansed, output_width=width, output_height=height)

    except Exception as e:
        print(f'Error attempting to render SVG to PNG using cairosvg:')
        print(e)

    return result

rendered_png_as_bytes = render_svg_and_return_bytes(svg_content_cleansed, width=224, height=224)

buf = BytesIO(rendered_png_as_bytes)
img = Image.open(buf)
img.save(f'cleansing_test_samples/1.png')
```

### The observations

The above code **fails** for at least the following sizes (width = height):

- 226
- 224
- 223
- 222
- 221
- 220
- 129
- 64

The above code **works just fine** and produces a PNG for at least the following sizes:

- 128
- 225 (!)

If I completely delete the pattern tag, then the PNG is created for all sizes.

**What the heck is going on?**

**Comment by liZe** [comment]
Hello! Thanks for reporting this issue.

I can reproduce your problem on Ubuntu.

> For some other unknown reason, this above error is not caught by my try / except clause and crashes the Python program.

This error is not caught because it’s a segmentation fault, not a problem in some Python code.

dmesg gives me this: `python[XXX]: segfault at XX ip XX sp XX error 4 in libpixman-1.so.0.38.4[XXX]`

It means that it’s probably a bug in libpixman.

I’ve installed libpixman version 40.0 (the version installed in my Ubuntu 20.04 is 38.4), and it fixes the problem. So… You can report a bug to Ubuntu and see if they can backport the fix into the 38.4 version, or you can live dangerously and install version 40.0 manually (it’s already [packaged for Ubuntu 21.04](https://packages.ubuntu.com/hirsute/libpixman-1-0)).
