### ISSUE TITLE
Incomplete conversion of the filled faces of svg in the process of converting to pdf file

### ISSUE THREAD

**Issue by luoyu-123** [Kozea/CairoSVG#331]
1.This is the svg picture：
![image](https://user-images.githubusercontent.com/59160360/121311583-20773680-c937-11eb-9398-139f908c54b9.png)

### 
2.This is the converted pdf file：
![image](https://user-images.githubusercontent.com/59160360/121311692-3dac0500-c937-11eb-8fee-c3a10e047a53.png)

Is there any way to solve this problem?

**Comment by liZe** [comment]
Hello! Could you please attach your SVG file?

**Comment by luoyu-123** [comment]
> 你好！你能附上你的SVG文件吗？

alright, thank you very much! This is the svg file


[svg-file.zip](https://github.com/Kozea/CairoSVG/files/6627744/svg-file.zip)

**Comment by liZe** [comment]
I get the right result with the latest version of CairoSVG (2.5.2). Is your version up to date, or do you use other options when generating the PNG file?
![444](https://user-images.githubusercontent.com/952243/121796584-70e1e300-cc1a-11eb-8107-fe363bc4cee6.png)

**Comment by luoyu-123** [comment]
Thank you very much for your help. I am also using the CairoSVG (2.5.2) version, but I want to convert to a pdf file instead of a png file.
Best wishes

**Comment by liZe** [comment]
The PDF file I get is also perfect.
[444.pdf](https://github.com/Kozea/CairoSVG/files/6653096/444.pdf)

**Comment by luoyu-123** [comment]
Thank you very much, I have also found the problem. It is my dpi value that is set high that will cause such a problem. , Thank you very much for your kind help.
Best wishes
