### ISSUE TITLE
__doc__ mangling causes CPython optimized mode to fail

### ISSUE THREAD

**Issue by rtpg** [Kozea/CairoSVG#336]
https://github.com/Kozea/CairoSVG/blob/49c53b3a1d59d8ba1236095505e6ffb70f9ddfcb/cairosvg/__init__.py#L99-L108

These lines expect objects' docstrings to be present, which isn't the case if you're running CPython in optimized mode (`-OO`). A test for the `__doc__` attribute (or for `__debug__`) would make it so that things could work as expected

**Comment by liZe** [comment]
@rtpg Thanks a lot for the bug report.

#174 was supposed to be a harmless change, but it looks like changes are never harmless :smile:. It reminds me [this famous XKCD strip](https://xkcd.com/1172/) (poke @Alphare).

**Comment by Alphare** [comment]
Funnily enough, we (Mercurial) had a user complaint just a few days ago about a bug in which extension code assumed some docstrings were present while a Gentoo build of `hg` removed them, so I feel your pain. :D

**Comment by liZe** [comment]
Fixed by #337.
