### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by mrmrfan** [Kozea/CairoSVG#342]
Occasionally, I have a problem like this. But I don't know how to share the problematic svg file. 

```
Traceback (most recent call last):
  File "main/test.py", line 57, in <module>
    cairosvg.svg2png(url='test/test.svg', write_to='test/test.png')
  File "C:\Users\mrmrfan\anaconda3\envs\crawler\lib\site-packages\cairosvg\__init__.py", line 55, in svg2png
    return surface.PNGSurface.convert(
  File "C:\Users\mrmrfan\anaconda3\envs\crawler\lib\site-packages\cairosvg\surface.py", line 131, in convert
    instance = cls(
  File "C:\Users\mrmrfan\anaconda3\envs\crawler\lib\site-packages\cairosvg\surface.py", line 223, in __init__
    self.draw(tree)
  File "C:\Users\mrmrfan\anaconda3\envs\crawler\lib\site-packages\cairosvg\surface.py", line 469, in draw
    self.draw(child)
  File "C:\Users\mrmrfan\anaconda3\envs\crawler\lib\site-packages\cairosvg\surface.py", line 464, in draw
    draw_markers(self, node)
  File "C:\Users\mrmrfan\anaconda3\envs\crawler\lib\site-packages\cairosvg\path.py", line 52, in draw_markers
    if marker_node.get('markerUnits') == 'userSpaceOnUse':
```

**Comment by mrmrfan** [comment]
> 
> 
> Occasionally, I have a problem like this. But I don't know how to share the problematic svg file.
> 
> ```
> Traceback (most recent call last):
>   File "main/test.py", line 57, in <module>
>     cairosvg.svg2png(url='test/test.svg', write_to='test/test.png')
>   File "C:\Users\mrmrfan\anaconda3\envs\crawler\lib\site-packages\cairosvg\__init__.py", line 55, in svg2png
>     return surface.PNGSurface.convert(
>   File "C:\Users\mrmrfan\anaconda3\envs\crawler\lib\site-packages\cairosvg\surface.py", line 131, in convert
>     instance = cls(
>   File "C:\Users\mrmrfan\anaconda3\envs\crawler\lib\site-packages\cairosvg\surface.py", line 223, in __init__
>     self.draw(tree)
>   File "C:\Users\mrmrfan\anaconda3\envs\crawler\lib\site-packages\cairosvg\surface.py", line 469, in draw
>     self.draw(child)
>   File "C:\Users\mrmrfan\anaconda3\envs\crawler\lib\site-packages\cairosvg\surface.py", line 464, in draw
>     draw_markers(self, node)
>   File "C:\Users\mrmrfan\anaconda3\envs\crawler\lib\site-packages\cairosvg\path.py", line 52, in draw_markers
>     if marker_node.get('markerUnits') == 'userSpaceOnUse':
> ```

**Comment by mrmrfan** [comment]
It turns out that there is an undefined `url(#dot)` in my svg file. The svg just looks fine in the web explorer. Maybe there could be more exception handling mechanism.
`marker-end="url(#dot)`

**Comment by mrmrfan** [comment]
or is there any support for `marker `in cairosvg?

**Comment by liZe** [comment]
Hello! Could you please share you SVG file?

**Comment by liZe** [comment]
> or is there any support for `marker `in cairosvg?

`marker` is pretty well supported.

> Maybe there could be more exception handling mechanism.

CairoSVG has [a pretty strong philosophy](https://cairosvg.org/documentation/#philosophy) about errors in SVG files. It often crashes when the image is not perfectly formed. So… It’s not a bug, it’s a feature :smile:.

**Comment by mrmrfan** [comment]
OK. Thank you!
