### ISSUE TITLE
Support for Hyperlinks in SVG Output

### ISSUE THREAD

**Issue by chr15t0ph** [Kozea/CairoSVG#345]
Hi, I am using poppler's pdftocairo for PDF to SVG conversion. Unfortunately any links are lost in the SVG output.

The poppler developers have informed me (https://gitlab.freedesktop.org/poppler/poppler/-/issues/259) that this is due to CairoSVG not supporting HyperLinks in SVG output.

(The missing support is to some extend backed by some older mail thread on your cairo mailing list: https://lists.cairographics.org/archives/cairo/2017-December/028473.html)

Thus, I wanted to humbly ask whether HyperLink support would be possible in Cairo for SVG output?

Kind regards
Christoph

**Comment by grewn0uille** [comment]
Hello!

Actually CairoSVG is a library which converts SVG files into other formats using Cairo.

What you need/use is the SVG export of Cairo. And that is Cairo.

So you should report your bug to Cairo: https://gitlab.freedesktop.org/cairo/cairo/ :)

**Comment by chr15t0ph** [comment]
Thank you!! :)

I create an issue in Cairo tracker and close this one.

**Comment by chr15t0ph** [comment]
(For future reference: https://gitlab.freedesktop.org/cairo/cairo/-/issues/509)
