### ISSUE TITLE
Svg Rendering Error

### ISSUE THREAD

**Issue by p3rd1x** [Kozea/CairoSVG#346]
I tried to use CairoSVG to render a svg image from Wikipedia to png.
The rendered result is very messy. Seems like the coordinates of some points got misplaced.

This is the original picture:
https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg

script is as simple as:
```
from cairosvg import svg2png
svg2png(
    url="https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg", 
    write_to="image.png", 
    output_height=1080
    )
```
This is the rendered image:
![image](https://user-images.githubusercontent.com/73039942/138784226-3a3bba26-bc63-411c-8284-1c85a6271f79.png)

**Comment by liZe** [comment]
It’s fixed on `master`, thanks for the report!
