### ISSUE TITLE
urllib.error.URLError when calling svg2png on an svg containing <image> with a relative path

### ISSUE THREAD

**Issue by vali19th** [Kozea/CairoSVG#353]
the solution I found is to go to the directory the SVG is stored in, call svg2png, go back to the directory you ran the script from
```
pwd = os.getcwd()
svg_dir = svg_path.rpartition('/')[0]

os.chdir(svg_dir)
cairosvg.svg2png(bytestring=svg_path, write_to=in_mem_file)
os.chdir(pwd) 
```
cairosvg 2.5.2
python 3.8.11

**Comment by liZe** [comment]
Hello!

If the SVG file is given to `svg2png` with no absolute path information, there’s no reliable way to resolve relative paths, for example the ones in `image`. Your example should work if you give `file_obj` or `url` instead of `bytestring`.

**Comment by vali19th** [comment]
Thank you for the explanation.
