### ISSUE TITLE
Doesn't render background

### ISSUE THREAD

**Issue by Lucianod28** [Kozea/CairoSVG#355]
Here's my code:
```python
import cairosvg

with open('out.png', 'wb') as f:
    cairosvg.svg2png('<svg width="100px" height="32px" style="border-radius: 8px 8px 0px 0px; background-color: rgb(232, 232, 232);"><g fill="none" fill-rule="nonzero"><rect width="100%" fill="#e8e8e8"></rect><circle stroke="#F04744" fill="#FF5F56" cx="20" cy="17" r="6"></circle><circle stroke="#EBA03F" fill="#FFBD2E" cx="40" cy="17" r="6"></circle><circle stroke="#13AB42" fill="#27C93F" cx="60" cy="17" r="6"></circle></g></svg>', write_to=f)
```
If I render the html I get this: https://jsfiddle.net/j3h9eoyz/. However, this is the resulting png:
![test_out](https://user-images.githubusercontent.com/19213351/150726239-d9e40d2f-3f82-49e1-a634-effec7b959c3.png)
Notice the grey background (`background-color: rgb(232, 232, 232)`) is missing. Does anyone know what's wrong here?

Edit: clarified problem

**Comment by liZe** [comment]
The `background-*` CSS properties are not supported. You’ll have to to use a filled rectangle to get a background.
