### ISSUE TITLE
converted png is black only

### ISSUE THREAD

**Issue by retsyo** [Kozea/CairoSVG#360]
I installed cairosvg/cairoffi/tinycss/cssselect on my python-3.8.1.amd64 on windows 10 b4 bits via
```
 pip install --upgrade --no-cache --force-reinstall cairocffi
 pip install --upgrade --no-cache --force-reinstall cairosvg
 pip install --upgrade --no-cache --force-reinstall tinycss
 pip install --upgrade --no-cache --force-reinstall cssselect
```
then I use
```
python-3.8.1.amd64/Scripts/cairosvg.exe  -f png -o 1.png 1.svg
```
to convert the svg file, which is attached here, into png. However, the png is all black

on the other hand
 ```
python-3.8.1.amd64/Scripts/cairosvg.exe  -f pdf -o 1.pdf 1.svg
```
creates a corrected pdf file

any hints?

Thanks

[1.zip](https://github.com/Kozea/CairoSVG/files/8401909/1.zip)

**Comment by liZe** [comment]
Hello!

Here’s what I get with your file, everything seems to be normal:
![1](https://user-images.githubusercontent.com/952243/161371144-7e40712d-968c-42c0-84a5-3e6f84a216e4.png)

Moreover, if you get a correct PDF, it probably means that there’s nothing wrong with CairoSVG, and that the problem comes from elsewhere. If you have installed GTK to get Cairo installed, you should probably try to update it.

**Comment by retsyo** [comment]
I give up

I am using MSYS2+MIngW64 on windows 10 64 bits, even I do `pacman -S mingw-w64-x86_64-gtk3`, the exported PNG is still black

**Comment by liZe** [comment]
That’s really strange…

Could you please provide the PNG and the PDF you get?

**Comment by retsyo** [comment]
here it is
[1.zip](https://github.com/Kozea/CairoSVG/files/8402480/1.zip)

**Comment by liZe** [comment]
Your PNG is totally OK for me:
![1](https://user-images.githubusercontent.com/952243/161389301-1b090ef4-32ca-4052-a3c8-529f706ec831.png)

As the PNG background is transparent, maybe the only problem you have is to display it on a black background…

**Comment by retsyo** [comment]
Aha, the black background is the answer. Thank you for your time and your CairoSVG.
