### ISSUE TITLE
Much Bigger After Converting (from 333.7kB to 1.4MB)

### ISSUE THREAD

**Issue by JianzhengLuo** [Kozea/CairoSVG#362]
Hello,
While using `cairosvg.svg2pdf()`, I figured that my SVG file is only 333.7kB but the converted PDF file is up to 1.4MB.
Why did this happen?

```python3
import cairosvg
cairosvg.svg2pdf(url="./test.svg", write_to="./test.pdf")
```
Files uploaded below.

[test.svg](https://user-images.githubusercontent.com/86510320/179021015-2d5d4c6a-0716-4814-84fb-0dc02e81abd2.svg)
[test.pdf](https://github.com/Kozea/CairoSVG/files/9113188/test.pdf)

![SVG File Rendered](https://user-images.githubusercontent.com/86510320/179021015-2d5d4c6a-0716-4814-84fb-0dc02e81abd2.svg)

**Comment by liZe** [comment]
Hi,

That’s because we decode/encode the image in an way that’s not optimized.

We probably won’t solve this in CairoSVG. You’ll get better results if you render your file in an HTML document using WeasyPrint, or with another SVG-to-PDF converter.

**Comment by JianzhengLuo** [comment]
I'd like so, but as a middle school student in China, I am still busy in summer vacation, but I will try my best!

**Comment by JianzhengLuo** [comment]
Thank you very much!
