### ISSUE TITLE
pytest-flake8 broke

### ISSUE THREAD

**Issue by stuaxo** [Kozea/CairoSVG#367]
pytest-flake8 removed ConfigFileFinder, breaking the tests in this and loads of other projects.
```
============================================================================================== short test summary info ==============================================================================================
FAILED setup.py::flake-8::FLAKE8 - AttributeError: module 'flake8.options.config' has no attribute 'ConfigFileFinder'
FAILED cairosvg/__init__.py::flake-8::FLAKE8 - AttributeError: module 'flake8.options.config' has no attribute 'ConfigFileFinder'
FAILED cairosvg/__main__.py::flake-8::FLAKE8 - AttributeError: module 'flake8.options.config' has no attribute 'ConfigFileFinder'
FAILED cairosvg/bounding_box.py::flake-8::FLAKE8 - AttributeError: module 'flake8.options.config' has no attribute 'ConfigFileFinder'
FAILED cairosvg/colors.py::flake-8::FLAKE8 - AttributeError: module 'flake8.options.config' has no attribute 'ConfigFileFinder'
```

**Comment by liZe** [comment]
Thanks for the report.

**Comment by stuaxo** [comment]
Thanks, thought If have a see if this could work with pycario with a little work, but the test thing was a blocker.

I like the way this does regression testing, it's pretty neat.

**Comment by stuaxo** [comment]
Wow, didn't realise you fixed this so fast.

I think `python setup.py test` broke along the way, it says, even though I have pytest in the virtualenv

```
/home/stu/.virtualenvs/cairosvg/lib/python3.8/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'console-scripts' will not be supported in future versions. Please use the underscore name 'console_scripts' instead
  warnings.warn(
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'pytest'```

**Comment by liZe** [comment]
> I think `python setup.py test` broke along the way, it says, even though I have pytest in the virtualenv

You’re right. Actually, I removed the whole `pytest-runner` dependency, as calling `setup.py` directly is deprecated. There’s a [nice blog article about this](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html).

Calling `pytest` is the best way to launch tests now. I didn’t update the README, it’s now fixed.

**Comment by stuaxo** [comment]
Cheers.
