### ISSUE TITLE
Possible to not install Pillow?

### ISSUE THREAD

**Issue by dunkmann00** [Kozea/CairoSVG#370]
Hello, first I have just found this library through [Pygal](https://github.com/Kozea/pygal) (which I also just found) and they are great. 

My main reason for using them and for finding them better than other options is because of how small (filesize) they are. I wanted to embed them in a small cli tool written in python that is frozen using `PyInstaller`.

This mostly works great, but I noticed that because this uses `Pillow`, it adds a relatively decent amount of size to the code. I realize as far as python projects go it isn't too big, but still significantly bigger than anything else that is required when using CairoSVG.

My question is if there is anyway you would consider making the `Pillow` dependency optional? I believe `Pillow` is used to process raster images that are in the svg. If a user knows they aren't dealing with svgs that have raster images in them, they don't actually use `Pillow`.

I looked through the code and realize this wouldn't be a trivial change. I was hoping to get your thoughts about this and would be happy to make a PR for this request if it is something you would be open to incorporating in?

Thanks!

**Comment by liZe** [comment]
Hi!

As explained in #298 and in this [blog article](https://www.courtbouillon.org/blog/00023-the-future-of-cairosvg), CairoSVG won’t change much, so there’s very little change such a modification will be included in CairoSVG soon 😒️. 

But if you really want to avoid to include Pillow, removing [this line](https://github.com/Kozea/CairoSVG/blob/adf1fd49478b3a99b7770295aa6086362cf8ed41/cairosvg/image.py#L9) before using PyInstaller is probably the only thing you need to do. If your users don’t have raster images in their SVG files, it should work flawlessly!

**Comment by dunkmann00** [comment]
Thanks @liZe for the feedback! That issue and blog post were very helpful to understand the status of the project so I totally understand why this wouldn't get accepted.

> But if you really want to avoid to include Pillow, removing [this line](https://github.com/Kozea/CairoSVG/blob/adf1fd49478b3a99b7770295aa6086362cf8ed41/cairosvg/image.py#L9) before using PyInstaller is probably the only thing you need to do. If your users don’t have raster images in their SVG files, it should work flawlessly!

Indeed it did! Thanks for the simple workaround 👍
