### ISSUE TITLE
No library called "libcairo-2" was found

### ISSUE THREAD

**Issue by udit-001** [Kozea/CairoSVG#371]
So I was trying to run CairoSVG in a docker container (python:3.9-slim-buster) with my python application, and I keep running into the error:
```
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': libcairo.so.2: cannot open shared object file: No such file or directory
cannot load library 'libcairo.2.dylib': libcairo.2.dylib: cannot open shared object file: No such file or directory
cannot load library 'libcairo-2.dll': libcairo-2.dll: cannot open shared object file: No such file or directory
```

I have got the following dependencies installed:
```
python3-cffi libffi-dev libcairo2 libcairo2-dev libpango-1.0-0 libpangocairo-1.0-0
```

Also, the docs refer to Weasyprint documentation for Linux dependencies but Weasyprint dropped CairoSVG as a dependency and hence no longer mention linux dependencies needed to work with CairoSVG. So, if you could update the documentation to include the same details, that would be great!

**Comment by liZe** [comment]
Hi!

> Also, the docs refer to Weasyprint documentation for Linux dependencies but Weasyprint dropped CairoSVG as a dependency and hence no longer mention linux dependencies needed to work with CairoSVG.

Even if WeasyPrint dropped CairoSVG as a dependency, you can still follow [WeasyPrint install steps on Windows](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows), and especially install GTK3 that will come with everything needed to use CairoSVG, including the Cairo library you’re missing.

**Comment by liZe** [comment]
The [`libcairo2` package](https://packages.debian.org/buster/amd64/libcairo2/filelist) includes `libcairo.so.2`, the file you need. If `/usr/lib/x86_64-linux-gnu/libcairo.so.2` is really on your system and Python’s not able to find it, then there’s definitely something wrong elsewhere and I’m not sure that I’ll be able to help :/. Did you change environment variables that could interfere with the way libraries are found on your system?

**Comment by udit-001** [comment]
I took at look at the contents of the directory : `/usr/lib/x86_64-linux-gnu/` and there's no file named `libcairo.so.2` present in it!

**Comment by liZe** [comment]
> I took at look at the contents of the directory : `/usr/lib/x86_64-linux-gnu/` and there's no file named `libcairo.so.2` present in it!

Then you did not install the libcairo2 package, did you?

**Comment by udit-001** [comment]
> > I took at look at the contents of the directory : `/usr/lib/x86_64-linux-gnu/` and there's no file named `libcairo.so.2` present in it!
> 
> Then you did not install the libcairo2 package, did you?

My bad, we had a multi stage build and I installed it in the wrong stage, just installing these two did the trick:
```
libcairo2 libcairo2-dev
```

**Comment by StefanoCecere** [comment]
i have the same problem, but on macOS, when upgrading to Python 3.11
and here it seems i can't install `libcairo2 libcairo2-dev`:

```
pip3 install libcairo2    
ERROR: Could not find a version that satisfies the requirement libcairo2 (from versions: none)
ERROR: No matching distribution found for libcairo2
```

**Comment by liZe** [comment]
> pip3 install libcairo2

Cairo is not a Python package, it can’t be installed with `pip`.

WeasyPrint is now packaged for Homebrew. [`brew install weasyprint`](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#macos) is the easiest way to get WeasyPrint working on macOS.

**Comment by StefanoCecere** [comment]
arg. it asks me to install all xcode commands... 40 hours download :!!!

**Comment by liZe** [comment]
> WeasyPrint is now packaged for Homebrew. [`brew install weasyprint`](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#macos) is the easiest way to get WeasyPrint working on macOS.

I’m sorry, I thought that you wanted to install WeasyPrint, not CairoSVG.

But you can still use Homebrew to install [Cairo](https://formulae.brew.sh/formula/cairo), and use Homebrew’s Python to install CairoSVG using `pip`.

**Comment by cporrasn** [comment]
I have the same problem, but on windows, with a python 3.8. Installing gtk3 from here: https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases is enough to solve the problem?

**Comment by mintisan** [comment]
When I use railway.app's VPS[linux], some issure occurs :


OSError: no library called "cairo-2" was found no library called "cairo" was found no library called "libcairo-2" was found cannot load library 'libcairo.so.2': libcairo.so.2: cannot open shared object file: No such file or directory cannot load library 'libcairo.2.dylib': libcairo.2.dylib: cannot open shared object file: No such file or directory cannot load library 'libcairo-2.dll': libcairo-2.dll: cannot open shared object file: No such file or directory


my requirements:
```
weasyprint
pillow
numpy
streamlit
cairosvg
```

**Comment by softmarshmallow** [comment]
> When I use railway.app's VPS[linux], some issure occurs :
> 
> OSError: no library called "cairo-2" was found no library called "cairo" was found no library called "libcairo-2" was found cannot load library 'libcairo.so.2': libcairo.so.2: cannot open shared object file: No such file or directory cannot load library 'libcairo.2.dylib': libcairo.2.dylib: cannot open shared object file: No such file or directory cannot load library 'libcairo-2.dll': libcairo-2.dll: cannot open shared object file: No such file or directory
> 
> my requirements:
> 
> ```
> weasyprint
> pillow
> numpy
> streamlit
> cairosvg
> ```

Same - deplaying my worker on railway. did you find a clean solution? @mintisan
