### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by Tc14Hd** [Kozea/CairoSVG#373]
I tried using mypy with CairoSVG, but it says that it's `missing library stubs or py.typed marker`. Are there any type annotations available for CairoSVG? And if not, is it possible to add those?

**Comment by liZe** [comment]
Hi!

> Are there any type annotations available for CairoSVG?

No.

> And if not, is it possible to add those?

Unpopular opinion: we’re not huge fans of annotations in Python. So, even if someone wanted to add them in a pull request, we’re not sure at all that we’d merge it.

Moreover, [CairoSVG won’t evolve that much in the future](https://www.courtbouillon.org/blog/00023-the-future-of-cairosvg), so we’re really conservative about changes that may include new bugs and/or more maintenance work.

**Comment by Tc14Hd** [comment]
Okay. Thank you for answering my question!
