### ISSUE TITLE
ClamAV found a virus in tarball

### ISSUE THREAD

**Issue by turtle-94** [Kozea/CairoSVG#378]
After we scanned our pypi we got the following message:
CairoSVG-2.6.0.tar.gz: Sanesecurity.Malware.26626.SvgHeur.UNOFFICIAL FOUND

Not sure if it is anything to worry about, but i let you guys know just in case.
I've also emailed Sanesecurity to get more information.

**Comment by turtle-94** [comment]
Sanesecurity told me this is a false positive

**Comment by liZe** [comment]
Thanks for the report.
