### ISSUE TITLE
CSS @import broken?

### ISSUE THREAD

**Issue by jmmelko** [Kozea/CairoSVG#379]
Hi,

I have used CairoSVG a few years ago and it supported @import CSS directives into the <style> tag.
Now, it does not seem to work anymore.

What I did:

- [X] Python 3.9.7
- [X] pillow 9.0.0
- [X] Latest Cairo '2.6.0'
- [X] tinycss2 installed, version '1.2.1'
- [X] cssselect2 installed, '0.7.0'
- [X] Tried to simplify the CSS file
- [X] Tried with and without CDATA around the import command
- [X] Checked that the CSS file worked with a Web Browser
- [X] Checked that style was used by CairoSVG if instead of using import, I copy-pasted the CSS file inside `<defs><style></style></defs>` inside the SVG file
- [X] Put everything in a single folder, used os.chdir, and did a simple command: cairosvg.svg2png(url='C.svg',write_to='C.png')
- [X] tried silly things such as adding or removing optional attributes in the SVG or XML tags

I am pretty sure it worked at some point ; unfortunately I could not find a test in cairo Github that uses external CSS.

I wish I could run cairoSVG in verbose mode.

---- SVG file -----
```
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" width="100" height="110" viewBox="0 0 100 110" xmlns="http://www.w3.org/2000/svg">
<defs>
<style type="text/css">
@import url('svg.css');
</style>
</defs>
<circle class="ps-fill" cx="50" cy="55" r="50" />
<circle class="ps" style="fill:none;stroke:white;stroke-width:8.3;" cx="50" cy="55" r="23.5" />
</svg>
```

---- CSS  file ----
```
svg .ps-fill, svg .ps-fill
{
	fill:rgb(4,80,124);
	filter: brightness(140%);
}

svg .ps-stroke, svg .sw-stroke
{
	stroke:rgb(4,80,124);
	filter: brightness(140%);
}
```

PNG output:
![C](https://user-images.githubusercontent.com/17069038/217876723-648af8ff-b43f-4f3b-84ae-c1e8f4ddef5a.png)

Expected output (obtained by moving manually the content of the CSS file):

![C](https://user-images.githubusercontent.com/17069038/217877799-99618900-8057-4ff7-9234-6023e7d0afaf.png)

**Comment by liZe** [comment]
Hi!

It doesn’t work anymore because of https://github.com/Kozea/tinycss2/issues/33.

A simple workaround is to use `@import 'svg.css'` or `@import url(svg.css)` instead.

**Comment by jmmelko** [comment]
Thank you so much!
I have changed it and it works.

However I have discovered that hsl(h, s, l) directives are not supported, it needs RGB
