### ISSUE TITLE
Embedded Images broken on Mac?

### ISSUE THREAD

**Issue by sebst3110** [Kozea/CairoSVG#389]
Hello,

at fist, I absolutely love your project, very nice one!

At the moment I'm experiencing issues using cairosvg when converting SVGs with embedded Images to PDF or PNG. I also tried the example given in the closed issue [https://github.com/Kozea/CairoSVG/issues/234#issue-424168956](url) on my system:

```python
import cairosvg

svg = """<?xml version="1.0" encoding="UTF-8"?>
<svg width="26mm" height="37mm" version="1.1" viewBox="0 0 26 37" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <g transform="translate(0,-260)">
  <image x="7.6102" y="267.88" width="2.6458" height="2.6458" preserveAspectRatio="none" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKAQMAAAC3/F3+AAAABlBMVEX///8AAABVwtN+AAAAEUlE QVQI12P4f4ABiHgYsCIAY1cD3831LVcAAAAASUVORK5CYII= "/>
  <text x="10.787534" y="270.40604" fill="#000000" font-family="sans-serif" font-size="3.4703px" letter-spacing="0px" stroke-width=".086757" word-spacing="0px" style="line-height:1.25" xml:space="preserve"><tspan x="10.787534" y="270.40604" stroke-width=".086757">EST</tspan></text>
 </g>
</svg>"""

png = cairosvg.svg2png(svg)
```

There are no errors during script execution, but the embedded image ist not showing up in the exported PDF / PNG.

Does anyone have any suggestions or a solution how to solve this problem?

Thank you so much guys.

**Comment by liZe** [comment]
I think that it’s a duplicate of #383. We have to release a new version, you can use `unsafe=True` as a workaround now (if your content is safe, of course).

**Comment by sebst3110** [comment]
Thank you so much, that worked for me!

Sorry for not getting, that this was a duplicate.

**Comment by sebst3110** [comment]
Thank you so much, that worked for me!

Sorry for not getting, that this was a duplicate.
