### ISSUE TITLE
Exception has occurred: ValueError could not convert string to float: '39px'

### ISSUE THREAD

**Issue by miro-balaz** [Kozea/CairoSVG#393]
`<svg height='39px' viewBox='0 0 40 39px' width='40' xmlns='http://www.w3.org/2000/svg'><rect x='0' y='38px' width='100' height='1' fill='#000000'/></svg>`

**Comment by grewn0uille** [comment]
Hello,

`viewBox` attribute [allows only numbers as values](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox#svg).
Managing malformed SVG files is not impossible, but it’s something [we don’t want to do](https://cairosvg.org/documentation/#philosophy).
