### ISSUE TITLE
svg2pdf export turns transparent background in black

### ISSUE THREAD

**Issue by anuj-scanova** [Kozea/CairoSVG#395]
Using this library to convert svg to pdf file using the following function
```
data = str(unquote(data, encoding='utf-8'))
data = cairosvg.svg2pdf(bytestring=data, unsafe=True)
```
and the data content is sent via API (edit file to view content)
![ file](https://github.com/Kozea/CairoSVG/assets/105233146/9d5e6b65-07d0-4128-a874-4513c2e9badc)

However, it generates black background

<img width="339" alt="Screenshot 2023-08-04 at 2 04 49 PM" src="https://github.com/Kozea/CairoSVG/assets/105233146/baae657f-3455-4e84-9ead-2a8a12834a1f">

while the expected output is

<img width="228" alt="Screenshot 2023-08-04 at 2 05 50 PM" src="https://github.com/Kozea/CairoSVG/assets/105233146/283407ab-aeac-4c3a-8e1d-da860a999cca">

**Comment by liZe** [comment]
Thanks for the bug report, it should be fixed now!

**Comment by anuj-scanova** [comment]
Thanks for looking into this. By when this change will be released? I need to use in my application.

**Comment by liZe** [comment]
> By when this change will be released?

It’s been released right now.

> I need to use in my application.

Don’t hesitate to [support us](https://opencollective.com/courtbouillon) if CairoSVG is useful for your application!
