### ISSUE TITLE
QR code with gradient color is broken when converted to png

### ISSUE THREAD

**Issue by duongnx25** [Kozea/CairoSVG#396]
Hi, when converting a QR code with gradient color, the content in the PNG file is broken and not readable anymore.

This is the SVG file:
![caba2102d16818b18e96b429cf44f5fbf27c26ed](https://github.com/Kozea/CairoSVG/assets/101819500/7a984b0f-6c48-4e33-8758-6ede99fffc2d)

This is the PNG file after converting:
![caba2102d16818b18e96b429cf44f5fbf27c26ed](https://github.com/Kozea/CairoSVG/assets/101819500/ee3d547a-db87-4315-bd95-6a5734e8e275)

I used the following code to convert the file
`cairosvg.svg2png(url= 'original_file.svg', write_to='converted.png')`
The same issue happens with svg2pdf.

**Comment by liZe** [comment]
Thanks for the bug report! It should be now fixed.

**Comment by duongnx25** [comment]
Awesome job @liZe! Tested and it's working like a charm!
