### ISSUE TITLE
Mention `output_width` and `output_height` function arguments in documentation

### ISSUE THREAD

**Issue by OLEGSHA** [Kozea/CairoSVG#401]
Currently, the [documentation](https://cairosvg.org/documentation/) contains the following paragraph:

> They can also receive these optional parameters corresponding to the command-line options:
> 
> - `parent_width`,
> - `parent_height`,
> - `dpi`,
> - `scale`, and
> - `unsafe`.

However, `output_width` and `output_height`, two important options present since 1a0eba6, are missing from this list. This can reasonably confuse the reader into thinking these options are not supported.

**Comment by liZe** [comment]
Thanks for the report, it’s fixed!
