### ISSUE TITLE
Truncating fractional height in pixels

### ISSUE THREAD

**Issue by judge2005** [Kozea/CairoSVG#414]
I was puzzled by an issue I was seeing where a SVG was being rendered nicely by inkscape, but when I use CairoSVG to convert it to a PNG it looked as though the last raster line was being discarded. I finally took a look inside the SVG and saw this:

```
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="53px" height="32.996px" viewBox="0 0 53 32.996" enable-background="new 0 0 53 32.996" xml:space="preserve">
```
Note the height is 32.996px! On a hunch I rounded it up to 33px and now the last raster is properly in the image.

This seems like a bit of an outlier, but I was confused as to why the image looked fine in inkscape but not after conversion by CairoSVG. Should CairoSVG have an option to round/floor/ceiling fractional pixel sizes? I note that the viewBox is fractional too, rounding that up has no noticeable effect on the image in this case.

This is a bit of a weird SVG, I have attached it below

![cloud-orig](https://github.com/Kozea/CairoSVG/assets/294515/2bc88f73-ce9a-4f02-b593-0ea31feb1faf)

And the result of running `cairosvg -f png -o cloud.png cloud-orig.svg` on it

![cloud](https://github.com/Kozea/CairoSVG/assets/294515/033b746a-2cf6-4088-a0a5-6bccc9edc13c)

This is the output if I modify the SVG to round the height in pixels up to 33:

![cloud](https://github.com/Kozea/CairoSVG/assets/294515/5916885a-8e04-40b5-8485-d1cf0cd98455)

The output is even better if I up the height in pixels to 34:

![cloud copy](https://github.com/Kozea/CairoSVG/assets/294515/5f97901e-dd78-41a6-a362-70998f073d6f)

I tried the -H option, but it has no effect on the output. Even if it did, it would be good to be able to specify the rounding as I need to convert many of these SVGs all with different heights. Perhaps a relative dimensions argument like `--delta_height 2`?

**Comment by liZe** [comment]
Yes, the size is [currently truncated](https://github.com/Kozea/CairoSVG/blob/051df1b44544e02d0670b2b193c5be47cb0a5311/cairosvg/surface.py#L524-L525).

It seems obvious that rounding would be a perfect idea … but it’s not :smile:.

If your SVG’s size is 10.5px, with a 10.5px white square for the background, you want to get a white PNG, and not semi-transparent pixels on the right and the bottom. So, unfortunately, rounding the surface size is not perfect in all cases.

What if we add a scale factor of 11/10.5 before rendering? That would avoid the transparent pixels (if floating point arithmetic gods love you), but we would lose pixel alignment and get blurry rendering even for horizontal and vertical lines. So, even rounding + scaling is not perfect.

So… I’m not sure about what to do here.

Even my image viewer is "broken" with this SVG file 😢
![Capture d’écran du 2024-03-06 14-37-06](https://github.com/Kozea/CairoSVG/assets/952243/e51f473a-0afd-498a-9f73-46401da09bd3)

Half pixels are devil.

**Comment by judge2005** [comment]
I think it would be easiest(?) to just provide options that allow the user to define what behavior they want, i.e. specify the rounding and/or specify a border to grow the rendering surface. That way the user has some tools to manage the conversion and you don't break the existing functionality.

**Comment by liZe** [comment]
Let’s round values. It’s not perfect, but nobody will ever complain. 😄

**Comment by liZe** [comment]
> Let’s round values. It’s not perfect, but nobody will ever complain. 😄

Except tests, of course…
