### ISSUE TITLE
Don't lowercase ids in CSS

### ISSUE THREAD

**Issue by emitc2h** [Kozea/CairoSVG#61]
Hello!

Inkscape generates linearGradients like the following:

    <linearGradient
       id="linearGradient3857">
      <stop
         style="stop-color:#e56e00;stop-opacity:1;"
         offset="0"
         id="stop3859" />
      <stop
         style="stop-color:#871500;stop-opacity:1;"
         offset="1"
         id="stop3861" />
    </linearGradient>
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient3857"
       id="linearGradient3863"
       x1="165"
       y1="157.36218"
       x2="165"
       y2="92.362183"
       gradientUnits="userSpaceOnUse" />

So essentially, the stops are defined in a first linearGradient definition and then a second linearGradient instance is created to give coordinates to those stops. The weird thing is that the Inkscape linearGradients do not render. Here's a minimal example that should reproduce the issue:

    <svg width="250" height="150" viewBox="0 0 250 150"
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink">
    
      <defs>
        <linearGradient
           id="linearGradient0011"
           x1="0"
           y1="0"
           x2="0"
           y2="150"
           gradientUnits="userSpaceOnUse">
          <stop
            offset="0%"
            style="stop-color: #000080; stop-opacity:1"/>
          <stop
            offset="100%"
            style="stop-color: #005cdb; stop-opacity:1"/>
        </linearGradient>
      </defs>
    
      <rect x="20" y="20" width="200" height="100"
        style="fill: url(#linearGradient0011);  stroke: black;"/>
    </svg>

If instead I simply replace "linearGradient0011" by anything else in this code, the gradient is actually rendered, so the following is correctly rendered for me:

    <svg width="250" height="150" viewBox="0 0 250 150"
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink">
    
      <defs>
        <linearGradient
           id="lolcat"
           x1="0"
           y1="0"
           x2="0"
           y2="150"
           gradientUnits="userSpaceOnUse">
          <stop
           offset="0%"
           style="stop-color: #000080; stop-opacity:1"/>
          <stop
            offset="100%"
            style="stop-color: #005cdb; stop-opacity:1"/>
        </linearGradient>
      </defs>
    
      <rect x="20" y="20" width="200" height="100"
        style="fill: url(#lolcat);  stroke: black;"/>
    </svg>

Simply in the interest of keeping compatibility with Inkscape, it would be nice to fix this issue. I'm trying to track it down myself, but since I'm not familiar at all with the code, anyone may be faster.Let me know if the problem is reproducible at all, I'm working on MacOS Yosemite. CairoSVG is really nice btw!

**Comment by kelvin13** [comment]
I found this bug independently, after much annoyance and searching, so this really needs to be fixed

**Comment by ErikOnBike** [comment]
Hi,

I created a fix for the case sensitivity. It's in a pull request right now. Existing tests still run okay.

Please let us know if this fixes your issues.

Cheers,
Erik

**Comment by liZe** [comment]
@kelvin13 @emitc2h Erik's pull request has been merged, and this problem seems to be fixed (at least the example given in the bug report). Feel free to reopen if another example doesn't work.
