### ISSUE TITLE
CairoSVG crashes with CAIRO_STATUS_WRITE_ERROR when a SVG has no absolute width, height or viewBox

### ISSUE THREAD

**Issue by tooh** [Kozea/CairoSVG#64]
https://github.com/SimonSapin/cairocffi/issues/49

**Comment by bjornarg** [comment]
What does your svg file look like?

**Comment by liZe** [comment]
CairoSVG doesn't know how to render files with no absolute width, height or viewBox. That's a know bug that wasn't in the issues list, thanks for reporting it!

Example:
```svg
<svg baseProfile="full" height="100%" version="1.1" width="100%"
     xmlns="http://www.w3.org/2000/svg">
  <circle cx="50" cy="50" r="40" />
</svg>
```

**Comment by brainstorm** [comment]
I'm getting the same error with the following SVG file:

https://gist.github.com/brainstorm/25f69d7a735f6e0127ff

**Comment by liZe** [comment]
Relative width and heights are now supported thanks to the `width` and `height` command-line options.
