### ISSUE TITLE
Use a single function to get filesystem and HTTP resources

### ISSUE THREAD

**Issue by mikeazo** [Kozea/CairoSVG#66]
There is a TODO for loading CSS from web url [here](https://github.com/Kozea/CairoSVG/blob/master/cairosvg/css.py#L49).

Any updates on when that will be done? It would be really useful.

**Comment by liZe** [comment]
We should write a single function that is able to handle at least file://, http:// and https://, and then use it everywhere (including href attributes).

**Comment by SimonSapin** [comment]
WeasyPrint does all this already. Are we ready to merge CairoSVG and WeasyPrint yet? :)

**Comment by liZe** [comment]
LOL. Actually, we should merge all these image makers into TeX.

**Comment by liZe** [comment]
It's been fixed in 1fee9268.
