### ISSUE TITLE
Doesn't support ANTIALIAS_FAST

### ISSUE THREAD

**Issue by integral-llc** [Kozea/CairoSVG#70]
Here is the error

```
CairoSVG-1.0.9/CairoSVG$ python cairosvg.py ../Comic/001_Teen.svg -f png > 1.png
Traceback (most recent call last):
  File "cairosvg.py", line 25, in <module>
    cairosvg.main()
  File "/home/dev/projects/CairoSVG-1.0.9/CairoSVG/cairosvg/__init__.py", line 93, in main
    SURFACES[output_format.upper()].convert(**kwargs)
  File "/home/dev/projects/CairoSVG-1.0.9/CairoSVG/cairosvg/surface/__init__.py", line 87, in convert
    cls(tree, output, dpi).finish()
  File "/home/dev/projects/CairoSVG-1.0.9/CairoSVG/cairosvg/surface/__init__.py", line 141, in __init__
    self.draw_root(tree)
  File "/home/dev/projects/CairoSVG-1.0.9/CairoSVG/cairosvg/surface/__init__.py", line 194, in draw_root
    self.draw(node)
  File "/home/dev/projects/CairoSVG-1.0.9/CairoSVG/cairosvg/surface/__init__.py", line 324, in draw
    "optimizeSpeed": cairo.ANTIALIAS_FAST,
AttributeError: 'module' object has no attribute 'ANTIALIAS_FAST'
```

here is the file to test
https://www.amazon.com/clouddrive/share/y-J77coa6eM_HdI9iluJeAU_B8MpRRMUJkhuxZSRxow?ref_=cd_share_link_copy

**Comment by liZe** [comment]
That's probably because you're using an old version of Cairo, do you know the exact version you're using?

**Comment by integral-llc** [comment]
This

```
import cairo

if __name__ == "__main__":
	print cairo.cairo_version_string()
```
returns 1.13.1

**Comment by liZe** [comment]
According to the documentation, `cairo.ANTIALIAS_FAST` is available since 1.12. I can convert your SVG sample without any problem with 1.14.2.

If it's possible you should update Cairo, as 1.13.1 is not even tagged in the git repository and is not available among the official releases.

**Comment by integral-llc** [comment]
you are right, I installed 1.14.2 and now it worked. However it has issues to create the right png.
See this picture, on the left is original and on the right the PNG result, looks terrible. 

![cairo-svg-ong](https://cloud.githubusercontent.com/assets/1841073/8273076/c1e4e530-1812-11e5-89ab-a305f4f0e62b.png)

just use the original file I attached when I created the question.

Am I missing something else?
thx

**Comment by liZe** [comment]
Yes, you need to install `lxml`, `tinycss` and `cssselect` when your SVG files have a CSS stylesheet (and your sample file has).

**Comment by integral-llc** [comment]
wow, thank you!
now it works as needed!

**Comment by liZe** [comment]
:)

**Comment by integral-llc** [comment]
it fails to convert such a file https://www.amazon.com/clouddrive/share/CbamTn-mNC4HIh7KNQMQi9pkiXXU_R85qKhtx4CwZ1A?ref_=cd_share_link_copy
it just hangs and eats all of the CPU
Can you please check?

**Comment by panamantis** [comment]
This fixed the issue for me on ubuntu: apt-get install python-cairo-dev

**Comment by Reshmakonjari112** [comment]
@integral-llc  can you please tell me how to upgrade the cairo because I'm getting an error "could not find the version that satisfies the requirement cariocffi(from versions)".
My cairo version is 1.12.18

Thanks in advance!!

**Comment by Reshmakonjari112** [comment]
Sorry I forgot to mention that I need it for Windows.

**Comment by liZe** [comment]
@Reshmakonjari112 There's a [GTK+ for Windows Runtime Environment Installer](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer) with cairo 1.14.6.
