### ISSUE TITLE
Cairosvg doesn't support unicode

### ISSUE THREAD

**Issue by tsingyi** [Kozea/CairoSVG#72]
I have some Chinese characters in my svg file, just like:

<img width="501" alt="screen shot 2015-08-19 at 10 34 04 am" src="https://cloud.githubusercontent.com/assets/6947982/9347570/01b43f52-465e-11e5-9edf-6a93beba5a70.png">

when I use cairosvg to convert the svg to png, I got a result like bellow:

<img width="473" alt="screen shot 2015-08-19 at 10 34 41 am" src="https://cloud.githubusercontent.com/assets/6947982/9347583/316ec988-465e-11e5-87b5-c9f0c25b0b39.png">

my svg file is encoding in `utf-8` format, is there any way to make Cairosvg convert unicode characters correctlly?

**Comment by liZe** [comment]
It's probably a problem related to fonts, not unicode. CairoSVG doesn't automatically find fallback fonts when the default font misses some characters. Please try to set a font-family property (with a font with Chinese characters), it should work.

**Comment by tsingyi** [comment]
Thanks, After try on another Ubuntu system, I think it's something related to fonts too, cause the svg is rend correctly on a desktop ubuntu, but would fail when on a ubuntu server edition environment.

**Comment by SimonSapin** [comment]
Servers typically don’t have many fonts installed (if any). Try installing some Chinese fonts on that server?

**Comment by jiafujiang** [comment]
Got the same issue.

**Comment by liZe** [comment]
> Got the same issue.

Installing fonts on your system should fix this issue.

**Comment by jiafujiang** [comment]
> > Got the same issue.
> 
> Installing fonts on your system should fix this issue.

How to install, is there any document?

**Comment by liZe** [comment]
> How to install, is there any document?

It depends, what’s your OS?

**Comment by jiafujiang** [comment]
> > How to install, is there any document?
> 
> It depends, what’s your OS?

I hope to use it on both Mac and Windows.
But is ok if only one of them can work.

**Comment by liZe** [comment]
> I hope to use it on both Mac and Windows.
> But is ok if only one of them can work.

Oh, I thought that you had an obscure Linux distribution :D.

You can install a font just you would normally do. On Windows, you can right-click on the font and choose "install for all users". On macOS, you can follow the [official support page](https://support.apple.com/en-us/HT201749).

**Comment by jiafujiang** [comment]
> > I hope to use it on both Mac and Windows.
> > But is ok if only one of them can work.
> 
> Oh, I thought that you had an obscure Linux distribution :D.
> 
> You can install a font just you would normally do. On Windows, you can right-click on the font and choose "install for all users". On macOS, you can follow the [official support page](https://support.apple.com/en-us/HT201749).

I think I have installed many fonts in my Mac, here is my font book:
![image](https://user-images.githubusercontent.com/10705142/103506529-e7263080-4e97-11eb-947d-92689a840046.png)

Do I need more configuration? For example, how can I set the font that cairosvg uses?

**Comment by liZe** [comment]
> For example, how can I set the font that cairosvg uses?

You have to use the [`font-family`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-family) property in the `text` tag.

**Comment by jiafujiang** [comment]
> > For example, how can I set the font that cairosvg uses?
> 
> You have to use the [`font-family`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-family) property in the `text` tag.

Thank you! I solve the problem.

Before generating the .svg file, I must set the font-family to a font which supports Chinese. Now I set the font-family to "Heiti SC Medium", and it can support Chinese.

**Comment by eigen2017** [comment]
same issue，ubuntu server，how to install font？

**Comment by liZe** [comment]
> same issue，ubuntu server，how to install font？

You can find some information on Internet about that, this is not a support forum. 😄

https://askubuntu.com/questions/3697/how-do-i-install-fonts
