### ISSUE TITLE
Markers not working at all

### ISSUE THREAD

**Issue by mikeazo** [Kozea/CairoSVG#74]
I saw #24 which led me to believe that markers are at least somewhat supported, however I can't seem to figure out how to get them to work.

For example, take the SVG contained in [this JS Fiddle](http://jsfiddle.net/7mkx6esp/1/). All I end up with is the blue line, no start or end markers after converting to PDF.

I was trying this on linux with the latest release.

**Comment by liZe** [comment]
Thanks for reporting.

CairoSVG really sucks at markers. Your really simple example hits 2 bugs:
- One is #61 and can be fixed by either using lower-case ids or using `marker-*` attributes instead of `style`.
- The other one is fixed in 55a7f07 (1.0.17 has been released).
