### ISSUE TITLE
The viewBox attribute does not work correctly in nested SVGs.

### ISSUE THREAD

**Issue by lukesneeringer** [Kozea/CairoSVG#79]
Given a nested SVG where the inner SVG has a viewbox but no explicit width or height:

```svg
<svg height="500" viewBox="0 0 500 500" width="597" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <svg viewBox="0 0 100 100">
    <circle cx="50" cy="50" r="50" fill="#0000ff" />
  </svg>
</svg>
```

The internal SVG should scale to the width and height of the outer SVG; therefore, the SVG above should output a 500 pixel blue circle. You can observe this by viewing that SVG in any browser.

In cairosvg, it does not do this; the autoscaling does not happen and you get a 100 pixel circle instead. The coordinate system in the internal SVG is not properly translated to the outer SVG.

**Comment by liZe** [comment]
Thanks for reporting! That's a known bug/feature reported and explained in #14.

**Comment by lukesneeringer** [comment]
That's not really an explanation. It's a stub saying that there needs to be an explanation. :-/

**Comment by liZe** [comment]
The documentation of the failing tests (the link in the linked issue) is the explaination: nested `svg` tags are used to create pages in CairoSVG, that's why they are not managed according to the specification.

**Comment by liZe** [comment]
#14 is fixed in master.
