### ISSUE TITLE
CairoSVG incorrectly converts this svg image to png

### ISSUE THREAD

**Issue by phalgun** [Kozea/CairoSVG#81]
Hi there, 

I'm using CairoSVG and noticed that an issue. When I try to convert this file http://pasteboard.co/2Ipcmv1B.svg+xml to png, the library gives me http://pasteboard.co/2Ipe0fSb.png

As you see, the final png is completely filled and doesn't have the same filling as the svg file.  Am I doing something wrong? 

Here is the code snippet I use

```python
cairosvg.svg2png(bytestring=svg_image_data, write_to=a_file)
```

This happens with only this particular svg file and not with others. 

Thank you for such a great library!

**Comment by liZe** [comment]
It works for me :).

You probably didn't install `lxml`, `cssselect` and `tinycss`, these 3 libraries are needed if you want to apply CSS to the SVG files. You can install them with pip.

**Comment by phalgun** [comment]
Yup, started working now. 

Thank you. I have another issue to report and will raise a new issue for that.
