### ISSUE TITLE
dlopen() failed to load a library: cairo / cairo-2

### ISSUE THREAD

**Issue by marvinmirtschin** [Kozea/CairoSVG#84]
```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cairosvg\surface\__init__.py", line 25, in <module>
    import cairocffi as cairo
  File "C:\Python34\lib\site-packages\cairocffi\__init__.py", line 46, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2')
  File "C:\Python34\lib\site-packages\cairocffi\__init__.py", line 43, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\marvin.mirtschin\Documents\cairotest.py", line 1, in <module>
    import cairosvg
  File "C:\Python34\lib\site-packages\cairosvg\__init__.py", line 27, in <module>
    from . import surface
  File "C:\Python34\lib\site-packages\cairosvg\surface\__init__.py", line 30, in <module>
    import cairo  # pycairo
ImportError: No module named 'cairo'
```
I read in an issue before, you can you cairocffi or pycairo but cffi seems not to work for me.

**Comment by liZe** [comment]
Looks like you don't have cairo installed.

As explained on [the cairo download page](http://cairographics.org/download/), the official way to install cairo seems to be to install Gtk+.

They are currently different Gtk+ installers, such as:
- http://www.gtk.org/download/windows.php (preferred solution based on MSYS2)
- https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer (almost up-to-date installer, for 64bit systems)
- http://gtk-win.sourceforge.net/home/index.php/Main/Downloads (quite old)

**Comment by marvinmirtschin** [comment]
Thanks a lot !

**Comment by liZe** [comment]
@marvinmirtschin Just for the record, which version of the installer did you use?

**Comment by marvinmirtschin** [comment]
I used the [GTK2-Runtime](http://lvserver.ugent.be/gtk-win64/gtk2-runtime) installer.
It's the one you get to from https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer

**Comment by zhaojigang** [comment]
@marvinmirtschin I meet the same error 
"OSError: dlopen() failed to load a library: cairo / cairo-2"
How did you solve it?

**Comment by Quixotica** [comment]
I still have this issue. I have followed instructions from:
https://gist.github.com/doobeh/3188318
http://stackoverflow.com/questions/38556368/getting-oserror-dlopen-failed-to-load-a-library-cairo-cairo-2-on-windows

Everything installed fine, just cannot `import weasyprint` without getting the dreaded dlopen() error :/

I'm thinking its something to do with my path, but everything there seems fine too. GTK+2/bin is on the path, as instructed.

**Comment by liZe** [comment]
Correctly installing Cairo on Windows is a nightmare. Being careful about 32/64bit seems to be important. You can follow **very carefully** the steps of the [WeasyPrint documentation](http://weasyprint.readthedocs.io/en/latest/install.html#windows) and see if it helps.

**Comment by bzamecnik** [comment]
On OS X (eg. El Capitan) this helped me:

```shell
export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:/usr/local/lib
```

**Comment by gclsoft** [comment]
@liZe I've installed gtk, and add `C:\Work2\msys64\mingw64\bin` to the PATH. But still `OSError: dlopen() failed to load a library: cairo / cairo-2`

**Comment by gclsoft** [comment]
I've installed `https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer` and set PATH. But still failed at `OSError: dlopen() failed to load a library: cairo / cairo-2`

**Comment by MarcG046** [comment]
I had also Inkscape installed which has its own libcairo-2.dll and appeared before GTK in the PATH
(discovered it by debugging through  cairocffi\__init__.py)
Changing the order in the PATH 'solved' it for me.

**Comment by kinkoazc** [comment]
Yup, make sure the Python<->GTK archs match up.

**Comment by apacha** [comment]
If you think, you've installed everything correctly, you can verify this, but running
```python
import ctypes.util
ctypes.util.find_library('cairo')
ctypes.util.find_library('cairo-2')
ctypes.util.find_library('libcairo-2')
```
And see, which one has the correct path. If only `libcairo-2` has the correct path, you might have to edit `%PYTHON_HOME%\Lib\site-packages\cairocffi\__init__.py` and add 'libcairo-2' into that list. At least, this fixed the problem for me.

**Comment by sega97** [comment]
On Win7, changing the order in the PATH 'solved' it for me. Put the GTK path before Python path.

**Comment by marius778** [comment]
I did execute, recommended by a user above.

export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:/usr/local/lib

How can I reverse it?

Thanks

**Comment by johncrosby** [comment]
This helped me on a mac: https://weasyprint.readthedocs.io/en/stable/install.html#macos
