### ISSUE TITLE
symbol elements should not be rendered

### ISSUE THREAD

**Issue by e-kwsm** [Kozea/CairoSVG#85]
According to [the standard](http://www.w3.org/TR/SVG/struct.html#SymbolElement),
> ‘symbol’ elements are never rendered directly

but CairoSVG *does*; besides, width and height are not changed.

For example, CairoSVG (1.0.19, Debian) convert
```svg
<svg viewBox="0 0 100 100"
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink">
  <symbol id="s" viewBox="0 0 100 100" preserveAspectRatio="none">
    <rect x="10" y="10" width="80" height="80" style="stroke:black;fill:none;stroke-width:5"/>
  </symbol>
  <use xlink:href="#s" x="50" y="50" width="40" height="10"/>
</svg>
```
to  
![a](https://cloud.githubusercontent.com/assets/11627708/12646929/33db18d8-c616-11e5-99d0-4980bad28cc2.png)

**Comment by liZe** [comment]
It's already fixed in current git version!
