### ISSUE TITLE
Documentation for -W -H are misleading 

### ISSUE THREAD

**Issue by lfx** [Kozea/CairoSVG#87]
Hello,
I noticed that [documentation](http://cairosvg.org/documentation/) states that is possible to resize image with -W or -H flags, but as far as I see from commit logs this feature is for v2.0 only, which are not yet realised. Pip installs version 1.0.19. 
Not a big problem, just confusing and for new users it may look like tool is broken. 

Thanks for the tool! :)

**Comment by liZe** [comment]
Thanks for the report! I've backported the feature in 1.0.x (I actually need it for WeasyPrint by the way).
