### ISSUE TITLE
Not support class style in css

### ISSUE THREAD

**Issue by whyb** [Kozea/CairoSVG#90]
Hello Kozea,

source svg file context:
```html
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 10 14" width="100px" height="140px" style="enable-background:new 0 0 10 14;" xml:space="preserve">
<style type="text/css">
.st0{fill:#FF00FF;}
</style>
<g>
	<path class="st0" d="M5.2,0.6h3.2v7.8h1.6v2.3H8.4V13H5.6v-2.3H0.7V8L5.2,0.6z M5.6,3.2L2.5,8.4h3.2V3.2z"/>
</g>
</svg>
```
But I call this function, it get test1.png's color was black(#000000).
```python
cairosvg.svg2png(url='svg1.svg', write_to='test1.png')
```
very thanks to this repository
Best Regards

**Comment by liZe** [comment]
It works for me. You should try to install `lxml`, `tinycss` and `cssselect` (with pip), they are needed to apply CSS.

**Comment by whyb** [comment]
As you said steps, I reinstalled them, That's OK now.
thank very much

**Comment by whyb** [comment]
Hello @liZe ,
Ask a few questions again please, I want update css in runtime, example:
```python
svg_tree = cairosvg.parser.Tree(url=fileurl)
for index in range(0, len(svg_tree.children)):
        if svg_tree.children[index].tag.lower() == "style":
            svg_tree.children[index].text = ".st0{fill:#ff0000;}"    #update css fill color to #ff0000
png_surface = cairosvg.surface.PNGSurface( svg_tree, "output.png")
png_surface.finish()
```
My codes is right? if not what should I do? Thanks@@
Best Regards

**Comment by liZe** [comment]
You should parse the SVG and modify it with `ElementTree` before giving it to CairoSVG's `Tree`, that's the best way to do this!

**Comment by whyb** [comment]
Fixed, As you suggest, I was modify svg file string before load CairoSVG's Tree.
Successful now.

```python
def __replaceStyle(string, colors):
        return re.sub(pattern=r"<style type=\"text/css\">(.+?)</style>", repl=".st0{fill:#ff0000;}", string=string, flags=re.IGNORECASE|re.MULTILINE|re.DOTALL)
```
God bless you@@
