### ISSUE TITLE
Text lines have mark when PDF is imported into CorelDraw

### ISSUE THREAD

**Issue by goosehub** [Kozea/CairoSVG#92]
I started a StackOverflow question here.

http://stackoverflow.com/questions/36284755/last-cursor-movement-recorded

I am using CairoSVG to turn an SVG into a PDF. I have found a bug where each line of text has a 1 dimensional mark at the end when the PDF is loaded into CorelDraw. 

![cairo-corel-issue-example](https://cloud.githubusercontent.com/assets/8077694/14108399/3c70ebae-f58b-11e5-94cf-ac70aa6ade52.PNG)

I find this is true even with the simplest and barest of SVGs. I then decided to dig into the python source of CairoSVG to fix the issue at it's root. I have found text.py to be the place where the issue occurs.

https://github.com/Kozea/CairoSVG/blob/master/cairosvg/text.py

Specifically, the `for [x, y, dx, dy, r], letter in letters_positions:` for loop. I can actually manipulate the mark by doing this after the for loop.

    surface.context.move_to( 100, 100 )
    surface.context.save()
    surface.context.text_path(' ')            
    surface.context.restore()

Depending on the values I enter, it will move one of the points (in this case the lower right point of the mark). This suggests that when CairoSVG is done with a line of text, the surface will move the cursor to the start of the last letter it was drawing. For some reason, the last time it does this is actually recorded into the PDF, although for most PDF viewers it does not render. I have tried to fine tune this mark so the two points are the same, but because this location is different each time depending on letter and location and more, I can't fine tune this number to make the mark disappear, even when using available width and height variables

Note that surface.context is not a file or function and surface is `pprint`ed as `<cairosvg.surface.PDFSurface object at 0x7f647802ec90>`, it's some  sort of Cairo interface for interacting with the PDF file directly through some sort of PDF API, although I haven't found any documentation on it.

I have tried lots of cheap work arounds, like saving the PDF in another program then opening in Corel, however elements are lost or altered in ways that are not acceptable.

I have also of course tried commenting out this file 1 line at a time, then chunks of code at a time, but with no luck.

I have also looked into other files such as path.py, parser.py, and more, but text.py seems to be the most promising location.

**Comment by liZe** [comment]
I've tried with many PDF renderers and I can't reproduce your problem, and I don't see anything wrong in `text.py`, so… I think that your problem is caused by a bug in Corel Draw, that doesn't like the way Cairo draws the letters :cry:. If you see the bug happening with other softwares, I can try to find the root of the problem, but otherwise, I'm afraid that you have to report it to the Corel team.

You can also try to use PS files instead of PDF and see if Corel Draw likes them better.
