### ISSUE TITLE
pip install pycairo does not provide a .bat file on windows

### ISSUE THREAD

**Issue by GadgetSteve** [Kozea/CairoSVG#95]
Installing with pip install pycairo provides a pycairo python shell script but not a .bat script so inexperienced python users on windows will not be able to execute from the command line.

**Comment by GadgetSteve** [comment]
I suggest taking a look at https://matthew-brett.github.io/pydagogue/installing_scripts.html which includes sections on automatic creation of both .exe and .bat files as a part of the install process.

**Comment by liZe** [comment]
Hmmm… This project is not pycairo, it's CairoSVG!

**Comment by GadgetSteve** [comment]
Sorry for the noise - closing.
