### ISSUE TITLE
textPath with spaces causes abort trap.

### ISSUE THREAD

**Issue by davenquinn** [Kozea/CairoSVG#99]
Text on path with spaces causes an abort trap using cairosvg version 1.0.20 (current on PyPi)
Replicated using `cairo` versions 1.14, 1.15, and current HEAD (`e825f59`)
I'm uncertain if this is an upstream bug in `cairo`...

In `cairo` HEAD:
```
> cairosvg -o test.pdf test. svg
Assertion failed: (!scaled_font->cache_frozen), function _cairo_scaled_glyph_page_destroy, file cairo-scaled-font.c, line 459.
[1]    50892 abort      cairosvg -o test.pdf test.svg
```
yields the above error message and produces no output

`cairosvg -o test-no-spaces.pdf test-no-spaces.svg` works fine.

See [this gist](https://gist.github.com/davenquinn/d2ba1ada38abcc313beb676d81bd6682) for test files.

**Comment by liZe** [comment]
I can't reproduce with:
- Gentoo Linux x86-64
- Python 3.4.3
- Cairo 1.14.6

Any idea about what's different for you?

**Comment by liZe** [comment]
This [Google search](https://encrypted.google.com/search?hl=fr&q="_cairo_scaled_glyph_page_destroy,%20file%20cairo-scaled-font.c,%20line%20459") is interesting (but not that useful).

**Comment by ErikOnBike** [comment]
Daven,

Are you on a Mac by any change? I had the same issue. I fixed it in text.py which is part of the current (recent) version of CairoSVG.

Please check it out and let us know if it is fixed.

Cheers,
Erik

**Comment by davenquinn** [comment]
Yes, Mac. I'll check again but I replicated it in `HEAD`

**Comment by liZe** [comment]
@davenquinn Is this bug fixed for you?

**Comment by liZe** [comment]
No news is good news.
